### ISSUE TITLE
Limitations like systemd/systemctl are not mentioned

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/WSL#1001]
The page mentions features like "Full Linux Kernel" and "Full system call compatibility" but there is no mention of system services that will/do not function. 

I am running [CentOS 7](https://github.com/wsldl-pg/CentWSL) using WSL2
```
PS C:\Users\test> wsl -l -v
  NAME                   STATE           VERSION
* CentOS7                Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
PS C:\Users\test>

```

and I find that systemctl returns error preventing normal use:
```
[root@MK ~]# systemctl
Failed to get D-Bus connection: Operation not permitted
[root@MK ~]# systemctl status nfslock
Failed to get D-Bus connection: Operation not permitted
[root@MK ~]#

```
It would be good to detail the limitations of WSL2 and also provide a roadmap for those limitations so that adopters can make informed decisions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [Comparing WSL 2 and WSL 1](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hi @kmathewmk ! The statements "Full Linux kernel" and "100% system call compatibility" are still accurate statements even though WSL doesn't come with systemd support out of the box. This is because WSL really does have [a full Linux kernel](https://github.com/microsoft/WSL2-Linux-Kernel) in it! The problem here lies within userspace. We run our own init process, and don't yet have support for systemd straight out of the box (though you can run it with some workarounds like [this community post](https://discourse.ubuntu.com/t/using-snapd-in-wsl2/12113) shows). 

I think your feedback is righteous that we should indicate somewhere our roadmap. In general we use the [Command line blog](https://aka.ms/cliblog) to show what's coming up, but perhaps this could be a good thing to put on our docs too.

**Comment by kmathewmk** [comment]
Thanks @craigloewen-msft for the details. It is good that we are getting closer to running standard Linux using WSL. 

Considering the problems I encountered, it think some more work is needed before WSL can be adopted in the enterprise. Built-in support for systemd, bridge networking etc are important for enterprise users looking for stability and compatibility. 

As someone wanting to make the switch, I would prefer to be informed upfront about WSL's limitations (and roadmap) rather than discover them one by one.

**Comment by craigloewen-msft** [comment]
Systemctl is now discussed in full and supported by WSL!
