### ISSUE TITLE
.wslconfig file examples

### ISSUE THREAD

**Issue by jlegue** [MicrosoftDocs/WSL#1064]
It would be much more helpful if there were specific examples for all of the valid parmeters that can be used as configuration directives in the .wslconfig file, especially for kernelCommandLine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Would it help if we added an example for kernelCommandLine to the example at the top? :)

**Comment by Biswa96** [comment]
I can't remember specifically but in a video cinnamon-msft showed a default json settings/template thingy for Windows Terminal. I would like to see that kind of single page documentation for .wslconfig and wsl.conf. Also with supported Windows build.

**Comment by Cloud2Software** [comment]
@craigloewen-msft - having valid examples for each of the directives would give some understanding to users as to how each is used. I found through trial and error that the following works:

kernelCommandLine=sysctl -w vm.max_map_count=262144

This was something that I had been looking for for months as when using Sonarqube in Docker under WSL2 the host VM that all the containers run in has the default vm.max_map_count value which is too low for Elastic Search. It may not need manual intervention if the above is in the .wslconfig file. This means that restarting after the many Windows 10 patches are pushed are that little bit less bothersome.

**Comment by jlegue** [comment]
On a reboot test after putting in place the line:

kernelCommandLine=sysctl -w vm.max_map_count=262144

The setting was still at the default of 65k so not a solution, but
something has to work and knowing what can be used in kernelCommandLine
would be beneficial.

**Comment by ev-dev** [comment]
Hey WSL maintainers super gracious for all the continued work y'all have been up to!

I'd just like to echo the issue raised by @jlegue because as you'll find in this repo, there are now many issues raised regarding `.wslconfig` confusions. 

Including the comments made by users here, there are several other legitimate concerns over correct syntax & needing better understanding of the `.wslconfig` config file. I didn't get the chance to comb thru all of them but just as an example, both #1189 & #1201 are asking for clarity on the memory parameter. 

@craigloewen-msft please consider rallying an effort to improve the documentation of this file with more details on each option's possible values. Most of us understand the WSL team(s?) like any other is constrained, but **a few minor efforts around the docs by those with the knowledge could really help a lot of users!**

**Comment by ev-dev** [comment]
>...could really help a lot of users!

And probably goes without saying, this in turn helps to boost WSL/Windows' reputation/adoption alongside as well! 😉

**Comment by jlegue** [comment]
Clearer docs on this file will definitely make it easier to adopt. As it stands I am very close to switching back from WSL2 to the legacy Hyper-V configuration as it would start up more consistently and I was more easily able to adjust resources used etc. If the .wslconfig file is better understood and documented it will definitely make it easier to make the decision to stay on WSL2.
