### ISSUE TITLE
Enabling Virtual Machine Platform caused all command boxes to crash upon start

### ISSUE THREAD

**Issue by sandybradley** [MicrosoftDocs/WSL#1139]
This step ...

dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

is bullshit.

Causes many crashes which are impossible to fix. Now I can't load any command window ( my entire work), I can't load wsl and I can't load any powershell. What's more, my time doesn't display or any admin windows to change settings.

**Comment by sandybradley** [comment]
![image](https://user-images.githubusercontent.com/29037794/113480798-85756280-9496-11eb-8e1c-ee01163529c9.png)

**Comment by craigloewen-msft** [comment]
Hi! This issue is a technical issue related to WSL. This repo is just for managing issues relating specifically to the WSL docs pages. If you're still experiencing this issue please file it at https://github.com/microsoft/WSL , the relevant info there will help us give you an actionable solution.

Thank you for filing!
