### ISSUE TITLE
Windows does not activate Windows Subsystem for Linux.

### ISSUE THREAD

**Issue by Funmoring46** [MicrosoftDocs/WSL#1151]
When I type `dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart` in PowerShell it says `Error: 2
An error occurred while attempting to start the servicing process for the image located at C:\.
For more information, review the log file.
The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log`

Can you please help me? The same error happens when I type `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart`.

When I install the Linux kernel update package, it shows this: 
![image](https://user-images.githubusercontent.com/71857158/114285117-7a2bb500-9a09-11eb-8588-951d1497337b.png)

And this:

![image](https://user-images.githubusercontent.com/71857158/114285127-831c8680-9a09-11eb-844d-69bff011c75a.png)

Please help me.

**Comment by craigloewen-msft** [comment]
We've put fixes here, please try this again and see if you're resolved (If not you can also try the Store version at https://aka.ms/wslstorepage ) 

Hi! This issue is a technical issue related to WSL. This repo is just for managing issues relating specifically to the WSL docs pages. If you're still experiencing this issue please file it at https://github.com/microsoft/WSL , the relevant info there will help us give you an actionable solution.

Thank you for filing!
