### ISSUE TITLE
Error downloading wsl.

### ISSUE THREAD

**Issue by FlinxDa1** [MicrosoftDocs/WSL#1177]
![image](https://user-images.githubusercontent.com/78230425/117362288-102bf180-ae89-11eb-82e3-82d8ee3982f2.png)
Can anyone help me? I have enabled both of those. Also when I restart after doing these two commands:
![image](https://user-images.githubusercontent.com/78230425/117362688-934d4780-ae89-11eb-9fc5-d7f8918f49df.png)

**Comment by Querynalhabsyi** [comment]
Where's the error?

**Comment by FlinxDa1** [comment]
So basically I get a blue screen when I do the commands and restart. The only way to revert that is with safemode or redownloading my OS.

**Comment by craigloewen-msft** [comment]
Hi! This issue is a technical issue related to WSL. This repo is just for managing issues relating specifically to the WSL docs pages. If you're still experiencing this issue please file it at https://github.com/microsoft/WSL , the relevant info there will help us give you an actionable solution.

Thank you for filing!
