### ISSUE TITLE
Please update WSL installation steps

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/WSL#1182]
The steps described on the mentioned page seem heavily outdated.

Please update, so new users can learn how to install and use WSL in 2021, with 20H2 and newer versions of Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by justkamiii** [comment]
What do you mean? I just followed as advised on the official docs and everything just worked for me. Can you explain furthermore?

**Comment by SetTrend** [comment]
Hello @justkamiii,

here are some passages that appear quite outdated and inaccurate for current Windows 10 installations (I'll use screenshot snippets in the following because it's easier for me to highlight passages therein):

![grafik](https://user-images.githubusercontent.com/9283914/120403687-fd4ff400-c344-11eb-9563-630eae064108.png)

![grafik](https://user-images.githubusercontent.com/9283914/120403869-633c7b80-c345-11eb-8f9b-cb731d6b8382.png)

![grafik](https://user-images.githubusercontent.com/9283914/120404041-c3cbb880-c345-11eb-8a93-149198c26511.png)

**Comment by Querynalhabsyi** [comment]
i skipped that, just check win + r -> winver.
It turned out that my version was updated, no need to open those links.

**Comment by mattwojo** [comment]
Hi @SetTrend - These instructions are accurate and current for WSL installation on modern versions of Windows. The `wsl --install` command is only currently available on Windows Insiders releases. We wanted to include it in the installation instructions because it has been helpful to see data and hear feedback from folks using that command so that it can be dialed in before being rolled out to general release. If you don't want to run an Insiders build of Windows, just follow the manual install steps: https://docs.microsoft.com/en-us/windows/wsl/install-win10#manual-installation-steps

*Also, some users have a specific need for running WSL 1, so we continue to support both WSL 1 & 2, though we recommend using WSL 2 unless you have a specific reason not to.

**Comment by SetTrend** [comment]
@mattwojo:

Hmm, OK ... Then I probably don't get the content of that page.

To enable WSL I simply use the Windows Features GUI:

![Container](https://user-images.githubusercontent.com/9283914/121504500-59201a00-c9e2-11eb-9b58-4884d06fc224.png)
![WSL](https://user-images.githubusercontent.com/9283914/121504515-5b827400-c9e2-11eb-8411-92f946721843.png)

**Comment by SimpleSamples** [comment]
> Hi @SetTrend - These instructions are accurate and current for WSL installation on modern versions of Windows. The `wsl --install` command is only currently available on Windows Insiders releases.

The instructions do not say that a Windows Insiders release is **required**. It implies that joining the Windows Insiders release is optional. It says:

_Try the most recent features or updates to WSL by joining the Windows Insiders Program. Once you have joined Windows Insiders, you can choose the channel_
