### ISSUE TITLE
npm start is not working on wsl but works on powershell(i.e: nodemon is not working whenever there is a change in files the app or server will restart but its not working on wsl ) 

### ISSUE THREAD

**Issue by Ajay-droid-cmd** [MicrosoftDocs/WSL#1211]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc9a77f-e6a1-a719-c337-7ff7506a1ac8
* Version Independent ID: 7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
* Content: [Install WSL on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Not quite understanding the issue here. A couple of suggestions are to ensure you have Node / nodemon and everything you're using installed in your WSL Linux distro. PowerShell would be using Node from your Windows OS installation, not an installation on a WSL-installed Linux distro.
You can find more about getting Node set up with WSL here: https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl
