### ISSUE TITLE
Kali Linux installing problem Error: 0x80370102 

### ISSUE THREAD

**Issue by ahk52899** [MicrosoftDocs/WSL#1431]
So I'm trying to install Kali Linux. It seems like it is working and than after it loads I get Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

Press any key to continue...

I checked Hyper-V is enabled, Virtual Machine Platform enabled, wsl subsystem for linux enabled. What am I doing wrong?

in Power shell first I did wsl --list --online than the came up. I then put in  wsl --install -d kali-linux. It did download kali-linux but then i got that error.

**Comment by crramirez** [comment]
Check your task manager if virtualization is enabled: 
![image](https://user-images.githubusercontent.com/8397379/150652661-775dfebb-1099-4816-873c-c85f81c27145.png)
 If not go to your BIOS and try to enable it.

**Comment by ahk52899** [comment]
virtualization is enabled. SO how do I fix the problem to be able to update Kali?

**Comment by crramirez** [comment]
Check if ti is useful to you: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues/78#issuecomment-633363296

**Comment by craigloewen-msft** [comment]
Please check the virtualization troubleshooting steps:
https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

And if you're still seeing this issue please reopen it on the microsoft/wsl repo, this repo is just for docs issues.

Thanks!
