### ISSUE TITLE
kali error  ED444FF07D8D0BF6

### ISSUE THREAD

**Issue by ahk52899** [MicrosoftDocs/WSL#1438]
when I try to upgrade kali and I type in sudo apt-get update I get this message. 
Get:1 http://kali.download/kali kali-rolling InRelease [30.6 kB]
Err:1 http://kali.download/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://kali.download/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

Virtualization, wsl, hyper v are all enabled. So what am I missing ?

I don't have gnupg, gnupg2 and gnupg1 installed which according to my research is what i need to fix my problem.

**Comment by mattwojo** [comment]
It sounds like this issue is something more directly related to Kali. Maybe similar to this? https://bugs.kali.org/view.php?id=7557

Please try filing this issue on the Kali bug reporter (https://bugs.kali.org) as I don't believe there's anything we do on the WSL side -- and this repo is just for reporting issues requiring doc updates, so if it comes back around that there is a WSL update required, please file on the WSL product repo: https://github.com/Microsoft/wsl/issues

Thanks!!
