### ISSUE TITLE
wsl install error code 0x80072f7d

### ISSUE THREAD

**Issue by tszl004** [MicrosoftDocs/WSL#1458]
what's mean about this code? what can I do for fix it?

```
C:\Users\Administrator>wsl --install -d Ubuntu
正在下载: Ubuntu
安装过程中出现错误。分发名称: 'Ubuntu' 错误代码: 0x80072f7d]
```

**Comment by mattwojo** [comment]
Based on that error code it looks like this is a nested virtualization issue. Check the WSL Troubleshooting guide here: https://docs.microsoft.com/windows/wsl/troubleshooting#error-0x80370102-the-virtual-machine-could-not-be-started-because-a-required-feature-is-not-installed

You might also check out this response from another user who ran into the same error: https://superuser.com/questions/1678737/component-wsl-kernel-error-code-0x80072f7d-on-wsl-install
They say: "You need to own the Pro/Business version of Parallels and then you need to [enable nested virtualization](https://kb.parallels.com/en/125195). I removed WSL in "Add or remove program features", restarted and attempted to install WSL once more with wsl --install after enabling nested virtualization and it worked eventually."
