### ISSUE TITLE
Install Page Instructions Unsuccessful

### ISSUE THREAD

**Issue by coloradodeano** [MicrosoftDocs/WSL#1567]
### Documentation Issue

For this page: https://docs.microsoft.com/en-us/windows/wsl/install instructions do not install the product. Command is successful, but then during reboot, multiple "something didn't go as planned" errors pop-up and then "ubuntu" command in Powershell results in an "not recognized" error. Running Windows 11 OS build 22000.258.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

Is there an error log like /var/log/messages in Windows where errors wold get logged?

**Comment by nikocraft** [comment]
You are lucky, I do not get even that far... nothing happens when I run wsl --install on windows 10 pro

**Comment by NotTheDr01ds** [comment]
While I sympathize with your problem, this is not a documentation issue.  That's a WSL or Windows issue of some sort.  When working properly, `wsl --install` will (sorry to be obvious) install WSL.  The Documentation's job (for any documentation) is to document the *normal, expected behavior* of the product.  It can't (and shouldn't) anticipate every possible thing that can go wrong.

I'd recommend posting this on the WSL Github itself, or perhaps on [Super User](https://superuser.com), Reddit's WSL subreddit [r/bashonubuntuonwindows](https://www.reddit.com/r/bashonubuntuonwindows/), or another site.

**Comment by craigloewen-msft** [comment]
Please try again, we have made lots of improvements to WSL since this was filed. If you're still seeing an error please file it at github.com/microsoft/wsl as this repo is just for the docs. Thank you!
