### ISSUE TITLE
Need to Check if 'gnupg' is installed ot not

### ISSUE THREAD

**Issue by AhmedAbuwarda** [MicrosoftDocs/WSL#1569]
### Documentation Issue

Some ubuntu images require gnupg to be installed before step #no 3 in mongodb installation 

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database

### Suggested Improvements

Add this:
3. Check if `gnupg` is installed or not: `sudo apt install gnupg`

**Comment by NotTheDr01ds** [comment]
What Ubuntu release are you using that doesn't have that package pre-installed?  The [Install MongoDB](https://docs.microsoft.com/en-us/windows/wsl/tutorials/wsl-database#install-mongodb) section does point out that the instructions are for Ubuntu 20.04.

Also, the doc does start out at the top with the prerequisite (and link to) [Install WSL and create a user name and password for the Linux distribution](https://docs.microsoft.com/en-us/windows/wsl/install)].  That assumes that the user has installed a Store based distribution using `wsl --install` or followed the "Manual install", which also covers the Store installs.  Those images should always have the `gnupg` package preinstalled.

If you are using a `--import`'ed Ubuntu image, then yes, it might not have the package installed, but that would be outside the scope of the "Databases" doc, right?

The doc can't anticipate all possible use-cases, so it does put "constraints" in place where appropriate.  I think (but tell me if I'm wrong) that the Microsoft team has listed those constraints appropriately in this case.

Here's my recommendation -- If you are using a `wsl --import`ed image of some sort that doesn't have the `gnupg` package installed:

* Post a question on [Ask Ubuntu](https://askubuntu.com) with the error message you get if it isn't installed.  You can mention that you were following the Microsoft doc (and link to it).
* Tag it *windows-subsystem-for-linux* and *mongodb* (and any others that are relevant).
* Post your answer -- Simply that the image you were using didn't have `gnupg` installed, and installing it corrected the issue.
* Come back in 2 days to self-accept the answer (the Stack Exchange delay for a self-accept).

That's going to get the error message indexed by search engines so that anyone else having the problem can hopefully find it fairly quickly.

Again, the doc team can't anticipate every permutation/curveball that we users might throw at them, but we can do our part to make the "advanced" information easier to find.

Bonus - I'd definitely upvote this as useful on Ask Ubuntu.  I usually check the *windows-subsystem-for-linux* tag there at least daily.

Also a quick secondary note - You can directly link to the section of the doc that you are referring to using the "anchor".  Hover over "Install MongoDB" and you'll notice a paperclip icon next to it.  Right-click on that to copy the link directly to that section.

**Comment by AhmedAbuwarda** [comment]
Oh, I got it. it is  for Ubuntu 22.04
I will open a question in askubuntu.com to share she sol with others.

Thanks man you made my day. 💪
