### ISSUE TITLE
Technical incorrect information 

### ISSUE THREAD

**Issue by fadyanwar** [MicrosoftDocs/WSL#1570]
### Documentation Issue

On the WSL installation documentation article https://docs.microsoft.com/en-us/windows/wsl/install under section "Install Linux on Windows with WSL" it says, "WSL enables you to use Linux tools, like Bash or Grep" where grep is a shell command that available to bash which is a type of shell.

### Link to documentation page

https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by NotTheDr01ds** [comment]
That doesn't seem to me to be "technically incorrect".  A "shell" like Bash may be a specific type of Linux tool, but it's a definitely a tool.

Many tools under Linux have very different (and yet sometimes overlapping) abilities:

For instance:

* They can stop and wait for user input.  Some make use of this capability (e.g. bash, git, vim, python).  Others don't (e.g. grep, find).

* They can provide output to the user.  Okay, pretty much every tool provides output, but they don't have to ;-).  If a tool doesn't have any output whatsoever, it's probably malware.

* They can build on the "input/output" capability to act as a REPL (read-evaluate-print-loop).  Some do (e.g. bash, python, bc).  Others don't (e.g. ls, grep).

* They can take over the full screen using terminal control codes.  Some do (e.g. vim, tmux).  Others don't (e.g. bash, grep, find).

* They can execute (fork) other processes.  Some do (e.g. find, bash, python, vim, find).  Others don't (e.g. grep, ls).

And many others.   I'm not sure why we shouldn't consider Bash to be a "Linux tool".  Is it because it has a REPL that evaluates commands?  If so, then how would the calculator tool `bc` be classified?  Each math expression that you input into `bc` is a "command" that is evaluated and then prints output.

My (overly long) point is that it's probably not a useful exercise to try to classify Linux applications as "tool" or "not a tool" based on their capabilities.

**Comment by fadyanwar** [comment]
I think you missed the point here. The line in question refers to both bash and grep (i.e. "bash OR grep") as if bash doesn't already include grep as a command. It's not a choice of either use bash or grep, if you use bash, naturally it will come with grep command included.

**Comment by NotTheDr01ds** [comment]
> as if bash doesn't already include grep as a command.

@fadyanwar  You are correct that I missed that point, but just to clarify -- No the Bash shell does *not* include Grep.  Your *distribution* (such as Ubuntu) *may* include both Bash and Grep.  However, it's entirely possible to have *either* independently:

* You can have grep without using the Bash shell.  This is extremely common since many people use alternative shells such as Fish, Nushell, or Zsh.  Some distributions don't even come with Bash installed at all (e.g. Alpine).

* Conversely, t's entirely possible to have a Bash shell that doesn't include Grep.  This is *not* very common.  Since so many scripts rely on grep, pretty much every distribution includes it.  That said, I've personally created WSL distributions that don't include it for special uses.

Bash does include certain "built-in" commands, such as `alias`, `read`, `logout`, etc.  Some of these, such as `echo` and `printf` *also* exist as separate binaries.  For instance:

```
> type -a echo
echo is a shell builtin
echo is /usr/bin/echo
echo is /bin/echo
```

If you run `echo Hello`, then it uses the Bash built-in.  If you execute `/usr/bin/echo Hello`, then it uses the binary which comes first on the path.

However, `grep` is not a built-in:

```
> type -a grep
grep is aliased to `grep --color=auto'
grep is /usr/bin/grep
grep is /bin/grep
```

The alias (on Ubuntu, at least) is created in the `~/.bashrc`.  However, if the `/usr/bin/grep` doesn't exist (which it doesn't have to), then the alias won't work either.

**Comment by fadyanwar** [comment]
@NotTheDr01ds So are you saying since grep has a separate binary from bash then it ought to be treated as separate from bash or any shell interface in general, so it's a choice to use either bash or grep?

If that is correct then based on your explanation we can also go on and say, using WSL you can use bash or ls, or maybe, bash or mv, and we can continue on like this with potentially every command binary under /usr/bin. Would that be a fair assessment?

**Comment by NotTheDr01ds** [comment]
@fadyanwar  Absolutely, any binary could be considered a separate tool, and most are independent from any other.  The Microsoft team just picked two well-known ones as examples of tools you can run.  Yes, they could just as easily have picked "Git and Vim".  Or "Zsh and ls".  Or "MongoDB and any of (near) countless more combinations.  Any of these would be correct, good examples of Linux tools you can use under WSL.

Also, since you phrase it like that, it makes me think of another common use-case for WSL -- Invoking a binary without using a shell at all.  For instance, from PowerShell:

```
wsl --user root --exec grep -Iri cron /etc
```

You can see that Bash isn't even running in this type of invocation by exiting any existing WSL instance and running the following from PowerShell:

```
wsl --shutdown
wsl -e ps -dfH
```

You'll see that nothing is running other than the WSL `/init` and `ps`.

**Comment by craigloewen-msft** [comment]
Agreed on the distinction that bash and grep are different classes of tools in Linux. However both are tools, and were picked since they are famous, and often asked for, and often searched for. I don't plan to change this doc since we want to include bash and grep here as top level tools since they're commonly searched for, and I think explaining the details of why they are different isn't so pertinent to the install doc page. I'll close this issue out as I don't see any content changes here for the docs. 

@fadyanwar thank you for giving us your feedback here!
