### ISSUE TITLE
Lack of clarity on processors setting in .wslconfig

### ISSUE THREAD

**Issue by DonGlover** [MicrosoftDocs/WSL#1738]
### Documentation Issue

Does this mean:
1. Actual cpus ie if I have as system with two cpus I can set this to 1 or 2
2. Cores. If I have as system with 2 cpus with 16 cores, I can set this to a value between 1 and 16?
<html>
<body>

processors | number | The same number of processors on Windows | How many processors to assign to the WSL 2 VM.
-- | -- | -- | --

</body>
</html>

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig

### Suggested Improvements

Use CPU to specify processors and cores if you mean cores.

**Comment by craigloewen-msft** [comment]
We use the term processor here because this is reflecting the amount of logical processors that you have on the host machine! Adding nuance of "Core" vs. "Processor" vs. "CPU". vs. "Logical Processor" is beyond the scope for this doc. Thank you for the feedback here. We'll change the term in the doc to "logical processor".
