### ISSUE TITLE
wsl-config: I'm guessing systemd needs to be installed before use?

### ISSUE THREAD

**Issue by SamB** [MicrosoftDocs/WSL#1799]
### Documentation Issue

 I'm assuming that in order to use systemd in a distro, you first need it installed in that distro. (The only other possibility is that WSL magically grafts it in from elsewhere, which would presumably lead to version skew, tears, and suffering.)

However, not everyone likes to overthink things the way I do, so it might not occur to them that they might need to install it ("might" because it's entirely possible that it was installed already, depending on: what distro they're using, whether they themselves uninstalled it because it had been useless on WSL before, etc. etc.).

And if I'm wrong, and you *don't* need it installed, that's **definitely** something you should mention because things could get *really* strange in that case.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support

**Comment by craigloewen-msft** [comment]
Hi @SamB you're correct you would need Systemd installed in that distro to use it. We find that the majority of distros used by WSL users today do have systemd support which is why we didn't specifically call it out, so we can make sure the docs are concise and give the key information to the users. Thank you for filing this!
