### ISSUE TITLE
Why Linux has to live on %systemdrive%

### ISSUE THREAD

**Issue by horvan** [MicrosoftDocs/WSL#185]
Nowadays SSD-Storage is expensive. So where is the option to put the WSL outside of my windows Home drive to be able to get enough space for Linux and development?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3be148fb-e4a9-83b5-5b5a-7834eed7052f
* Version Independent ID: f583bc11-fe60-bb2c-af2b-dc0dae9fe81f
* Content: [Learn about the Windows Subsystem for Linux](https://docs.microsoft.com/de-de/windows/wsl/about)
* Content Source: [WSL/about.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/about.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by DarthSpock** [comment]
Well actually SATA-based SSDs have their price driven down by the new NVMe SSDs. This being said, it is necessary to install distros outside of the system drive. I believe you can do so via the official open-source 
 [WSL-DistroLauncher](https://github.com/Microsoft/WSL-distrolauncher/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+) by simply placing the `rootfs` of the compiled distro on a different drive. As far as installing via the Microsoft Store, it is dependent upon the UWP infrastructure, which doesn't support installing distros outside of system drive at this time due to mechanisms such as security that are borrowed by WSL and will require work by the UWP team to support moving distros installed via the Store. See https://github.com/Microsoft/WSL/issues/449.

**Comment by horvan** [comment]
Nice tipp for geeks like me but that's not an end-user solution. As Windows user I like to decide where to put my Linux without building a whole distro on my own,

**Comment by scooley** [comment]
I totally understand your frustration.  Letting you easily install WSL distros on a non-system drive is [on our radar](https://github.com/Microsoft/WSL/issues/449).

**Comment by Amitie10g** [comment]
Actually, the distros from Microsoft Store are not installed in %systemdrive% but %localappdata% (inside %homepath%, that you can even mount in another media like in Linux). You may perfectly move the roots or the whole package to another location and symlink it (with none running) (I have not tested it yet. Be aware if the files and their metadata are modified due the operation).
