### ISSUE TITLE
wsl --install fails on Window 11 from PowerShell run as Admin (wsl --list --online gets the same result)

### ISSUE THREAD

**Issue by savaged** [MicrosoftDocs/WSL#1850]
### Documentation Issue

```
PS C:\Windows\system32> wsl --install
wsl : The term 'wsl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wsl --install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (wsl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/install

### Suggested Improvements

Add troubleshooting guide for the first step.

**Comment by mattwojo** [comment]
Hi @savaged - What version of Windows are you running? This shouldn't be happening unless maybe the prereqs of running Windows 10 version 2004 and higher (Build 19041 and higher) or Windows 11 aren't met... are you running an older version of Windows?

**Comment by savaged** [comment]
> Hi @savaged - What version of Windows are you running? This shouldn't be happening unless maybe the prereqs of running Windows 10 version 2004 and higher (Build 19041 and higher) or Windows 11 aren't met... are you running an older version of Windows?

Hi Matt,
Windows 11 as stated in the issue title.

**Comment by mattwojo** [comment]
Hmm... there's something wrong in your set up then.  Could you please open a bug report on the WSL product repo? > https://github.com/microsoft/WSL/issues/new?assignees=&labels=&projects=&template=Bug_Report.yaml

I don't believe that this is an issue with the documentation, so I'm closing the issue here (though if you believe otherwise, please re-open it and let me know what you think should be updated).
