### ISSUE TITLE
Attaching a USB Device

### ISSUE THREAD

**Issue by alwzfolwd** [MicrosoftDocs/WSL#1881]
### Documentation Issue

List all of the USB devices connected to Windows by opening PowerShell in administrator mode and entering the command:

PowerShell

usbipd wsl list

This information is incorrect, when I run the command in Powershell in Administrator mode I get the following error:

"usbipd: error: The 'wsl' subcommand has been removed. Learn about the new syntax at https://learn.microsoft.com/windows/wsl/connect-usb#attach-a-usb-device."

Upon visiting the URL it seems to be the same page that directed me to use the WSL cammand. It however does not explain the new syntax or subcommand to be used.

### Link to documentation page

https://learn.microsoft.com/en-us/windows/wsl/connect-usb

### Suggested Improvements

Please provide the proper information for attaching a usb to the WSL system.

**Comment by k3113n** [comment]
FYI, just drop the 'wsl' part of the commands.

`usbipd list`

In my case, a -w (or --wsl) needed to be used for the attach command.

`usbipd attach --busid <busid> -w`

And also in my case, I needed to bind the device first so that it could be shared with WSL:

`usbipd bind -b <busid>`

All that said, I agree that the documentation should be updated.

**Comment by mattwojo** [comment]
Thanks for filing. Resolved in https://github.com/MicrosoftDocs/WSL/pull/1870

**Comment by alwzfolwd** [comment]
Thanks guys!
