### ISSUE TITLE
Not Supported In PowerShell 6.0

### ISSUE THREAD

**Issue by heybobm** [MicrosoftDocs/WSL#197]
Enable-WindowsOptionalFeature is not available in PowerShell 6.0.  Documentation should identify which PowerShell versions support the Enable-WindowsOptionalFeature command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install the Linux Subsystem on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Service: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by PTrenholme** [comment]
Um, I just was doing that with no problem. Did you remember to start the PS in administrative mode?

**Comment by heybobm** [comment]
This is a Windows 10 Pro (Build 1803) workstation.  Using PowerShell 6.0-.0 as Administator the "enable-windowsoptionalfeature" command is not available.  See Screen Shot Below:

[cid:50b415ee-25aa-4309-ad93-add35523052e]


________________________________

**Comment by TheDarkerPhantom** [comment]
As the author of this issue, sort of hinted at, **Enable-WindowsOptionalFeature** is not available to PowerShell 6.0 by design.  PowerShell 6 is the current version of PowerShell Core.  If you need to run **Enable-WindowsOptionalFeature**  it only works with the .NET version of PowerShell on Windows 10

**Comment by heybobm** [comment]
So it meets our standards to hint at requirements versus clearly state the requirements in the documentation.


On May 16, 2018, at 9:42 AM, TheDarkerPhantom <notifications@github.com<mailto:notifications@github.com>> wrote:


As the author of this issue, sort of hinted at, Enable-WindowsOptionalFeature is not available to PowerShell 6.0 by design. PowerShell 6 is the current version of PowerShell Core. If you need to run Enable-WindowsOptionalFeature it only works with the .NET version of PowerShell on Windows 10

**Comment by bitcrazed** [comment]
From the opening paragraph of the [PowerShell Core 6.0 release announcement](https://blogs.msdn.microsoft.com/powershell/2018/01/10/powershell-core-6-0-generally-available-ga-and-supported/): 

> PowerShell Core 6.0 is a new edition of PowerShell that is cross-platform (Windows, macOS, and Linux), open-source, and built for heterogeneous environments and the hybrid cloud.

PowerShell Core is cross-platform and thus does not include some Windows-specific features that would not work on non-Windows platforms - for example, `Enable-WindowsOptionalFeature`.

Please read the post linked to above in its entirety - it goes on to differentiate where PowerShell and PowerShell Core differ, and shine.

Simple solution to this problem - use Windows PowerShell for administering Windows-specific features

**Comment by jmtread** [comment]
But...
_Joey Aiello, program manager and committee member of PowerShell 6.0, “Windows PowerShell 5.1, much like .NET Framework 4.x, will continue to be a built-in, supported component of Windows 10 and Windows Server 2016. However, it will likely not receive major feature updates or lower-priority bug fixes.”_
That sort of says that PS 5 will be left to rot over time. Surely at somepoint features like Enable-WindowsOptionalFeature are going to have to come over.

**Comment by bitcrazed** [comment]
"PS 5 will be left to rot over time".

No - rot is the wrong term here: Windows PowerShell is a critical piece of the Windows management and administration toolset. It'll still be serviced, updated and patched, but as with many critical OS components, it won't be getting any **_major_** new features.

Who knows, at some point in the future, when most/all of the necessary add-ins, libraries, packages, etc. have been ported to PowerShell Core, perhaps then Windows PowerShell will be retired to an optional component for those that want it for some legacy systems, but until then, Windows PowerShell will remain stable, secure, and central in Microsoft's management toolset.

So, until that time, if you want to write PowerShell scripts to administer, configure, or control _**Windows**_, I'd recommend focusing on using Windows PowerShell.

**Comment by jmtread** [comment]
Thankyou @bitcrazed for your time on my question. I do really appreciate it.
I was excited about PS6, but saddened that I have to switch between versions. I was hoping to make the leap to 6 and leave 5 behind and bring all my scripts up to ver 6 compatibility.

I understand now. I'll cross my fingers and hope the useful bits I use from ver 5 will find their way to 6.
In the mean time I'll have to make more use of these requires statements.
#Requires -Version <N>[.<n>]

Thanks again,

Jason

**Comment by bitcrazed** [comment]
No problem - really appreciate your enthusiasm, support and feedback - we thrive on feedback like yours!

Just realized I hadn't added @joeyaiello to the thread (sorry, chum) - since he's one of the key PM's on PowerShell, I think he may also find this discussion interesting.

Don't decrease your excitement about PSCore - it's where all the fun stuff is happening 😁 

I wouldn't be AT ALL surprised if @joeyaiello and team make features like this available, likely via a loadable PSCore module.

**Comment by joeyaiello** [comment]
Hey @jmtread! We've actually made it a *major* effort in this next shipping version of Windows 10/Server 2019 to port as many modules as possible to PowerShell Core (and validate/confirm the ones that already work great!). PowerShell Core is still going to be a side-by-side component that you have to install from the web, but compatible modules that are already in your Windows installation will have `CompatiblePSEditions` marked in their module manifests with `Core`, and then PowerShell Core will automatically pick them up as available modules. 

One of the big ones that people have been requesting is Active Directory, which now supports Core in the latest Insider builds of Win10 (after you install the RSAT optional feature), but a bunch more will be trickling in over the next few weeks. (Roughly 60% of modules should be marked as compatible by the next GA update, with more to come in future releases.)

There will be a repo available shortly at https://github.com/PowerShell/PowerShellModuleCoverage where you can file issues around modules you'd like to be supported in PowerShell Core, so that we can work with those teams to make it happen. 

Thanks for all of the interest! And if you have any other issues with PowerShell Core, come on over to https://github.com/powershell/powershell and file 'em!

/cc @SteveL-MSFT

**Comment by bitcrazed** [comment]
Thanks @joeyaiello & @stevel-msft  :) You guys (and your team) rock 😁

**Comment by SteveL-MSFT** [comment]
https://github.com/PowerShell/PowerShellModuleCoverage is open for business!
