### ISSUE TITLE
-wsl

### ISSUE THREAD

**Issue by drhassan20990** [MicrosoftDocs/WSL#1994]
### Type of issue

Code doesn't work

### Feedback

wsl is not work

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

drabdulqwi@hotmail.com

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a

**Comment by mattwojo** [comment]
Hi @drhassan20990 - Are you working in an Enterprise business setting? If so, you may want to check to see whether there may be permission blocks set up (these may be set up using Microsoft Intune, if so, here are the recommended settings for using WSL: https://learn.microsoft.com/en-us/windows/wsl/intune). 
If it's not an Enterprise setting issue, then you will need to provide more information and this doesn't appear to be a documentation issue, so I recommend filing your issue here: https://github.com/microsoft/WSL/issues
