### ISSUE TITLE
Why is not there Windows Terminal for windows server 2022 in Microsoft Store? 

### ISSUE THREAD

**Issue by guoshi2018** [MicrosoftDocs/WSL#2012]
### Type of issue

Missing information

### Feedback

    All WSL tools, not just “Windows Terminal”, such as “Fluent Terminal”, “deepin WSL” and so on, can not be run on Windows Server 2022. 
    For that he is brought up by his stepmother?
    Please help!

### Page URL

https://learn.microsoft.com/zh-cn/windows/wsl/setup/environment?source=docs

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/setup/environment.md

### Author

@craigloewen-msft

### Document Id

06d3a4ce-218a-d39d-4a71-60a3cb86e422

**Comment by mattwojo** [comment]
I don't understand the issue here. "WSL tools" is not a thing. Closing. Please feel welcome to reformat this issue to be more specific and reopen. 
If you are looking for how to install Windows Terminal on Windows Server 2022, see: [https://github.com/microsoft/terminal/discussions/13983](https://github.com/microsoft/terminal/discussions/13983).
