### ISSUE TITLE
Downloading via Cmdline

### ISSUE THREAD

**Issue by SolidOceanTrust** [MicrosoftDocs/WSL#256]
The 'Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1604 -OutFile Ubuntu.appx -UseBasicParsing' should be changed to '-Outfile Ubuntu.zip". The .appx extension is not associated to any application in W10 and does not open via the app store. Once it's a zip file, it can be extracted and the Ubuntu.exe appears and can be installed.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manually download Windows Subsystem for Linux (WSL) Distros](https://docs.microsoft.com/en-us/windows/wsl/install-manual)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-manual.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by gwojan** [comment]
The documented instructions work fine on Windows 10 1803. There is no need to name the install file as a .ZIP.

**Comment by alan23273850** [comment]
But it doesn't work on "Build 17134". It's indeed a zip file.

My situation is the following.
![xxxx](https://user-images.githubusercontent.com/10044077/44864113-6e07e480-acb1-11e8-9fb0-4dd1ebc9fdfb.png)

Maybe it's better to add some words to explain that the file format is "zip," for users from other versions.

**Comment by gwojan** [comment]
@alan23273850, You're absolutely correct, `.APPX` files are `.ZIP` files

```
4133> Get-WindowsVersion

ProductName           Version Build
-----------           ------- -----
Windows 10 Enterprise 1803    17134.228
```
I am using the same build but executing the `.APPX` file works correctly. May I ask how you downloaded the installer you're using? Yesterday, whenever I used Windows PowerShell 5.1 and `Invoke-WebRequest` the file download took forever and resulted in a corrupt `.APPX` and the same `Cannot open app package` message. `Invoke-WebRequest` from PowerShell Core 6.1 and `curl.exe` was blazing fast and the files were not corrupted.

I tested downloading the `.APPX` for Kali Linux today using Windows PowerShell 5.1 `Invoke-WebRequest` and the download was still really slow but the file was not corrupted.

As was explained [here](https://github.com/Microsoft/WSL/issues/449#issuecomment-415806817), you may have issues later if you use the server install instructions rather than allowing the `.APPX` installer to do its thing.

**Comment by alan23273850** [comment]
@gwojan , I have tried downloading both **(1)** by directly clicking on the link on the website and **(2)** with Windows PowerShell 5.1. Both of them generate **.zip** files.

I have succeeded in installing Ubuntu-18.04 right after realizing its format!

**Comment by zizifn** [comment]
Does anyone know how to uninstall this if i install by .zip?

**Comment by phmayer67** [comment]
After you download as zip: Expand-Archive -Path .\Ubuntu.zip -DestinationPath UbuntuInstall

Then from the UbuntuInstall directory run the ubuntu.exe

**Comment by mloskot** [comment]
Someone should close it, really

**Comment by craigloewen-msft** [comment]
Closed! All feedback in this thread has been added to the docs :)
