### ISSUE TITLE
Error: 0x80070005

### ISSUE THREAD

**Issue by eugeneniemand** [MicrosoftDocs/WSL#258]
I'm running Windows 10 Enterprise 1803 17134.112
```
Installing, this may take a few minutes...
Installation Failed!
Error: 0x80070005
Press any key to continue...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc0a885-286b-df36-acfd-f4afb5a33c9b
* Version Independent ID: 238333c7-116d-2697-702a-58fc7efe3ee9
* Content: [Install the Linux Subsystem on Windows Server](https://docs.microsoft.com/en-us/windows/wsl/install-on-server#download-a-linux-distro)
* Content Source: [WSL/install-on-server.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-on-server.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by Ajacs90** [comment]
I got this error too when I tried running openSUSE.
To fix it, I just ran as administrator.
I don't think you need to run as administrator for subsequent runs; maybe just to install it.

**Comment by longtth** [comment]
> I got this error too when I tried running openSUSE.
> To fix it, I just ran as administrator.
> I don't think you need to run as administrator for subsequent runs; maybe just to install it.

I choose to download then manual install 
running through an administartor Powershell but got `Error: 0x80070005` too

**Comment by ohryhorchuk** [comment]
I am having the same problem.
Downloaded via Powershell, unpacked and ran installer (as administrator).
Trying to install Ubuntu 18.04

**Comment by ohryhorchuk** [comment]
PS C:\dev\BD8026\linux\Ubuntu> .\ubuntu1804.exe
Installing, this may take a few minutes...
Error: 0x80070005
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: USER_NAME
Error: 0x80070005
Enter new UNIX username:

and it starts over

**Comment by milanjaros** [comment]
@ohryhorchuk, my initial installation ended the same as yours because I installed it as an Administrator. So, I: 
* changed permissions of the folder `C:\Tools\ubuntu`,
* unpacked files as non-Admin,
* executed `ubuntu1804.exe` as non-Admin 
... And installation finished successfully.

**Comment by craigloewen-msft** [comment]
I'm closing out this issue since there seems to be a solution. If it doesn't work please post a new issue on the WSL Github repo: https://github.com/microsoft/WSL as this repo is just for fixes to the WSL documentation. Thank you!

**Comment by mrboli** [comment]
I'm getting the same error.
Happens on "Enter new UNIX username"

I upgraded windows to 1903 and it still does this without the error code but still "Access is denied"
I'm doing it on another drive at the root of the drive and have done the

`icacls "C:\Users\Ansue\AppData\Local\Lxss" /grant "<username>:(OI)(CI)(F)"`
Command and also tried the 
`get-cipolicyinfo` but my system doesn't seem to have this command

I've also tried using mmc to create a group policy rule with full access for LxssManager

It DOES work in the regular local app data folder -- but I need it to not be there since I seem to frequently need to reformat, and my laptop needs a specific image of windows for the drivers, and updating everything for windows ends up taking 1-2 days (fucking annoying) so I need a windows image without ubuntu

**Comment by craigloewen-msft** [comment]
@mrboli I would recommend trying to use the `wsl --import` command to import your distribution, you can specify a custom install location in that command.

https://github.com/MicrosoftDocs/WSL/issues/412#issuecomment-501913246

**Comment by danielsouza** [comment]
@mrboli I solved this issue giving to all users and groups "Full Control" in the Linux folder, trough Security tab.
