### ISSUE TITLE
For Fall Creators Update and later

### ISSUE THREAD

**Issue by user77** [MicrosoftDocs/WSL#274]
After running the following command:
C:\&gt; ubuntu config --default-user root
You need to reboot, at which point your default user will be root. 
Another reboot is required after changing back to your default user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a09359b-8092-fb08-353c-ae03a91f26b6
* Version Independent ID: 6a9228f4-5240-8b14-3077-00340bcfdcf1
* Content: [Linux User Account and Permissions](https://docs.microsoft.com/en-us/windows/wsl/user-support)
* Content Source: [WSL/user-support.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/user-support.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by inkydragon** [comment]
more simple way：kill `wsl.exe` and `wslhost.exe`, then open `bash` and you will be root.

**Comment by craigloewen-msft** [comment]
In the latest builds you can use `wsl --shutdown` or `wsl --terminate` to ensure distros are terminated so you can rerun as the appropriate user.

WSL has gone through many updates and revisions, and this issue may be fixed in the latest version. We're cleaning out some of our older issues, and will mark this as closed. If you are still experiencing this issue on the latest version please feel free to reopen this! Thank you!
