### ISSUE TITLE
Distribution not found when changing name of user folder in windows

### ISSUE THREAD

**Issue by flurin-telepathy-ai** [MicrosoftDocs/WSL#297]
Hello

I have been using WSL for a while and I like it a lot. I tried renaming my user folder on windows following the steps below:
It seems that afterwards, no more linux distribution could be found on my computer. 
I am on Windows 10 1803 (17134.345). I have Ubuntu 18.04.1. 

The steps are:
https://support.microsoft.com/en-gb/help/2454362/renaming-a-user-account-does-not-automatically-change-the-profile-path
Basically, they are
1. Log in by using another administrative account.
2. Go to the C:\users\ folder and rename the sub folder with the original user name to the new user name.
3. Go to registry and modify the registry value ProfileImagePath to the new path name.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\&lt;User SID&gt;\

Is there a way I can point WSL to a different path to find my distro?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by RReverser** [comment]
Same issue; tried "Reset" in Apps & Features -> Debian -> Advanced options, that didn't help either.

**Comment by KharmaScribbles** [comment]
Did you guys:

4. Log out and log in again by using the user whose name is changed, and the user should use the pervious profile with new path name.

Other than that it may be an issue with the SID, are you using the correct one?

https://www.lifewire.com/how-to-find-a-users-security-identifier-sid-in-windows-2625149

Make sure in the registry editor you aren't changing the string verbatim to "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\/<User SID>" -- you want to leave that string alone since your user SID will not change just due to a username change, you want to actually edit the "Data" field of the ProfileImagePath to the new C:/User/NewUsername directory, and ensure you observe case.

After that, I suggest a reboot and login with the new user name :)

**Comment by craigloewen-msft** [comment]
WSL has gone through many updates and revisions, and this issue may be fixed in the latest version. We're cleaning out some of our older issues, and will mark this as closed. If you are still experiencing this issue on the latest version please feel free to reopen this! Thank you!

**Comment by redstreet** [comment]
Still fails exactly the same way. Solution is here: https://github.com/Microsoft/WSL/issues/3720
