### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by PRANEETHSWIFTGOULDING** [MicrosoftDocs/WSL#312]
Simply amazing. Very Helpful. The best solution provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Initialize a new WSL Linux distro](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro)
* Content Source: [WSL/initialize-distro.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/initialize-distro.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by JoFu2k191** [comment]
I always felt it was nonsens to flame Microsoft, espacially from the Linux community.
I have been working with Windows for decades and this is really an appricated features.
Some may say: "Why? whe have hypervisors!" 

Well, not knowing much about the WSL footprint I feel like it is rather small. Many Hypervisors are blown up for years I have my doubts about installing VMWare on my desktops for instance. Then there are situations you simple cannot install a hypervisor, company restrictions e.g. 

Good Work! I always trusted in Mircosoft. Nice to see something like this after my sabbat time ;)

**Comment by webtop** [comment]
People who flame Microsoft generally go home and turn on their Windows machine...complete flakes. The reason Linux never took of like Windows did, in the world outside of the geek universe, is simply because Microsoft did a far better job of presenting the user with things they could akin to real-world objects...I mean, the name is literally in the product! Windows, so you can view things!

I've been using Linux since it first came about, on an almost daily basis, but for ease of use I use Windows on a daily basis. Microsoft, quite simply has a far superior user experience in Windows, than any Linux distro.

**Comment by mscraigloewen** [comment]
Thank you for the positive feedback!

**Comment by heron1** [comment]
@webtop yes, it does. But I've always felt that linux had the better CLI. Why can't the two be married together with their respective strengths? Windows with the GUI, linux with the CLI. That would be the perfect marriage imho.
