### ISSUE TITLE
Accessing Linux files from Windows

### ISSUE THREAD

**Issue by tksharpless** [MicrosoftDocs/WSL#314]
Installed Debian under WLS and so far cannot find any trace of it in the Windows filesystem seen by File Explorer or Windows shells.  Two questions that should be answered by your docs:
1) How and where do you hide the Linux files?
2) Can PowerShell access them as Windows files?
I have used MinGW and Msys for years.  They don't need to put the 'nix filesystem in a ghetto; why should WLS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Initialize a new WSL Linux distro](https://docs.microsoft.com/en-us/windows/wsl/initialize-distro)
* Content Source: [WSL/initialize-distro.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/initialize-distro.md)
* Service: **windows-subsystem-for-linux**
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by DarthSpock** [comment]
You can't edit Linux files from windows. Only exception to that rule is VS Code. So no PS can't access them as windows files. They will show up in linux format. But since PS Core is cross-platform, you can use it for both as you can still use ps1 files no matter the platform. As for where Linux files are, they're hidden for a reason. Don't mess with them or you'll have to reinstall your distro. Only clue I'll give is it lives deep into your AppData folder. 

If you think .nix filesystem being available in Windows via WSL is ghetto then it isn't for you. But if you want to run Linux tools and apps natively, you need WSL or a VM. The things you mention can't do that and of the packages it does have, it doesn't support them nearly as well. WSL is a far better solution but you can learn that yourself.

**Comment by tksharpless** [comment]
Thanks for the clarification.  I guess WSL is not for me as I am interested in cross platform cooperation, not Native Linuxness.
