### ISSUE TITLE
WindowsOptionalFeature

### ISSUE THREAD

**Issue by Nevsimao** [MicrosoftDocs/WSL#343]
Enable-WindowsOptionalFeature : The referenced assembly could not be found.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
+ FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptinalFeatureCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @taraj
* Microsoft Alias: **taraj**

**Comment by Aleeeh** [comment]
open the powershell as an administrator and run the command. I had the same problem 😉

**Comment by marshjosh** [comment]
I am running it as administrator. Still same issue

**Comment by joegenius98** [comment]
https://serverfault.com/questions/464018/run-elevated-powershell-prompt-from-command-line

Apparently, running as an administrator is very strictly defined. I had the same error when I ran just from typing "Powershell" on the Windows search bar, and then using whatever popped up, because I thought by default I was running as administrator (maybe you were too?) . I followed the instructions from this link ^^ however, and it worked (you have to run a specific line in Powershell to run as administrator. You may have already done this and are unfortunately getting the same error, but I have not, so I believe this should work out for you).

**Comment by ChandanKSahu** [comment]
@joegenius98  It did not work for me. Still facing the same issue.
