### ISSUE TITLE
Ubuntu install packages without internet

### ISSUE THREAD

**Issue by purvinp** [MicrosoftDocs/WSL#372]
Hi

New to WSL.

I was able to offline install ubuntu 18x. I now need to add more packages but I do not have internet connection on my PC (locked behind FW). 

Can someone please help identify steps to get pacakges offline and then install them on the PC?

Thanks!

**Comment by mscraigloewen** [comment]
Hi @Almagnus1 , could you please open an issue on our WSL github page? We'll be able to help you over there, since this page is just for issues with the WSLDocs.

However for your problem I would recommend using the `wsl --import` and `wsl --export` functions to export a distro from a machine with internet access and import it into your current machine.

Thanks!
-Craig
