### ISSUE TITLE
Clearer Device Mapping

### ISSUE THREAD

**Issue by Almagnus1** [MicrosoftDocs/WSL#380]
I'm working with the ESP32 using https://github.com/espressif/esp-idf (which is a Linux toolchain), and it would be really nice if there was a clearer mapping of the Windows => Linux devices (specifically the USB ones), or documentation on where someone unfamiliar with Linux can find these as I'm not seeing where this is, and the usual Linux hooks aren't appearing to work.

**Comment by mscraigloewen** [comment]
Hi @Almagnus1 , could you please open an issue on our [WSL github page](https://github.com/microsoft/wsl/issues)? We'll be able to help you over there, since this page is just for issues with the WSLDocs. 

Thanks! 
-Craig

**Comment by Almagnus1** [comment]
@mscraigloewen IMO if you could point me to the correct doc page that goes over how WSL maps linux drivers to Windows, that would be ideal.  Since I'm seeing this as a doc issue, I'm not sure if that would make much sense.

**Comment by mscraigloewen** [comment]
Ah I see! My mistake, I misinterpreted your original request as a feature request. 

I'm opening this back up as yes that would be valuable to add in clearer instructions for device access.

**Comment by mattwojo** [comment]
Hi @Almagnus1 - I realize this issue is almost two years old now - sorry, there's so much to keep up with in regard to WSL and loads of issues. 
Does this doc explaining how to mount disks / devices address your issue here? Unfortunately USB flash drives and SD cards still aren't supported... but I believe that support is being worked on. Please re-open this issue and provide an example if what you're asking for isn't in this --mount doc: https://docs.microsoft.com/windows/wsl/wsl2-mount-disk
Thanks for contributing and apologies for the long delay.
