### ISSUE TITLE
How to pass the case-sensitive check when compiling the Android source code on WSL?

### ISSUE THREAD

**Issue by Micheal-Yan** [MicrosoftDocs/WSL#383]
【fsutil file setCaseSensitiveInfo】This command can only open the case of the current file, and its sub-files are still case-insensitive. This caused me to fail to pass the case-sensitive check when compiling the Android source code on WSL. How to solve this problem? @lizap @coreyp-at-msft

_Originally posted by @Micheal-Yan in https://github.com/MicrosoftDocs/windowsserverdocs/issues/977#issuecomment-487502350_

**Comment by jdorsay-xenu** [comment]
If your code is in an ntfs partition outside the wsl filesystem, cd to the root of the source tree and run this command as  an administrator. It will make the specified directory and all **existing** subdirectories case sensitive.

It is slow, even on an ssd, presumably because of the many file-system accesses.

`for /d /r %a in (**) do fsutil.exe file SetCaseSensitiveInfo %a enable`

**Comment by jdorsay-xenu** [comment]
This will make the specified directory and all **existing** subdirectories case sensitive.

It can be slow, even on an ssd. Presumably there are many scattered filesystem accesses.

Change to the root of the source tree, and run this as an administrator:

`for /d /r %a in (**) do fsutil.exe file SetCaseSensitiveInfo %a enable`

**Comment by Micheal-Yan** [comment]
@jdorsay-xenu Thanks a lot！
