### ISSUE TITLE
wslconfig /list lists nothing, yet I cannot remove/reinstall Kali

### ISSUE THREAD

**Issue by bndgzglln** [MicrosoftDocs/WSL#396]
I'm having issues installing Kali Linux. Installing fails in Error 0x80004005. Same with Ubuntu.
```
l:\> wslconfig  /l /all
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```
and
```
l:\> bash
Windows Subsystem for Linux has no installed distributions.
```

But Kali is present in my Start menu, and by reinstalling I am promted with "Already installed".
I've tried to disable and reenable WSL. No luck.
Also Installing Ubuntu fails in 0x80070005.

Anything that can be done here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [Manage Linux Distributions](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#feedback)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl-config.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @scooley
* Microsoft Alias: **scooley**

**Comment by bndgzglln** [comment]
SysInfo:
Windows 10 Enterprise
Version 1803
OS Build: 17134.619

Issue while running kali.exe:
```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070005
Error: 0x80070005 Access is denied.

Press any key to continue...
```
And if I run it as admin:
```
Installing, this may take a few minutes...
Error: 0x80070005
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: Test
Error: 0x80070005
Enter new UNIX username:
```

**Comment by mscraigloewen** [comment]
Hi @bndgzglln 

Could you please try running this command in a command prompt Window with administrator privileges:

`DISM /Online /Cleanup-Image /CheckHealth`

And then Uninstall the Kali app by right clicking on it and clicking uninstall, reinstall it and run that.

I'm going to close this issue since it isn't docs based, but if you still are running into this problem please open up another issue on the WSL github page: www.github.com/microsoft/wsl

Thanks!

**Comment by benhillis** [comment]
Also, wslconfig.exe /list /all

**Comment by comtechnet** [comment]
In my case - It works from both a windows cmd window (in admin mode) - and a powershell shell ( in admin mode) - I find that my default is docker-desktop-data (I have two others; docker-desktop and Ubuntu-20.04, so 3 total) - I was using docker to show some skills when applying for a job last year.  But I've forgotten the "root" password of my Ubuntu and can NOT apply any updates for the distribution.  Since my default is docker-desktop-data I wonder if I'm gonna mess it up - if it uses the root password for anyone of "it's" stuff/operations, hopefully it doesn't touch-use the Ubuntu at all (I would think not).  Hopefully if/once I get the Ubuntu root pw changed - I can get it updated.  So - not quite the same problem - but a little catch22 none the less.
