### ISSUE TITLE
wsl2 write  host disk so slowly

### ISSUE THREAD

**Issue by gao4263** [MicrosoftDocs/WSL#421]
i use dd test  wsl/wsl2  io performance

wsl :
dd if=/dev/zero   of=/mnt/e/test.df bs=8k count=2000000  conv=fdatasync
6277373952 bytes (6.3 GB, 5.8 GiB) copied, 24.5689 s, 256 MB/s

wsl2:
dd if=/dev/zero   of=/mnt/e/test.f  bs=8k count=2000000  conv=fdatasync

722993152 bytes (723 MB, 690 MiB) copied, 43.3944 s, 16.7 MB/s

how to tune to improve io performance

**Comment by mscraigloewen** [comment]
Improving Cross OS file system performance is high on our priority list and [we're working on it](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#cross-os-file-speed-will-be-slower-in-initial-preview-builds).

I'm closing out this issue since as of right now you aren't able to tune cross OS file system performance. Please stay tuned to new builds as we work on this experience, and if you have more questions feel free to reopen the issue or add comments.
