### ISSUE TITLE
wsl2 : docker containers can't access internet

### ISSUE THREAD

**Issue by nicolasdelvat** [MicrosoftDocs/WSL#422]
I just installed the new build (18917) to test wsl2 with docker.
![image](https://user-images.githubusercontent.com/51862431/59555029-b0827f80-8fac-11e9-886a-dbd503c3013a.png)
![image](https://user-images.githubusercontent.com/51862431/59555195-2ab40380-8faf-11e9-8da7-aa344d21c27b.png)

All commands calling the network in containers seems to not work properly. e.g.,
![image](https://user-images.githubusercontent.com/51862431/59555042-e0ca1e00-8fac-11e9-8c47-d53ec13c5e17.png)
![image](https://user-images.githubusercontent.com/51862431/59555385-7ff11480-8fb1-11e9-9f04-22e1046a9e00.png)

I don't have a corporate proxy or anything.

**Comment by StefanScherer** [comment]
Maybe the same as in https://github.com/microsoft/WSL/issues/4133
Some tried `--network host` or reinstalled ubuntu.

**Comment by nicolasdelvat** [comment]
You're right, this is the same issue.
At first, I installed the docker.io package with apt and it looks like there is a difference in the settings.
With the script [get.docker.com](https://get.docker.com/), it work like a charm now, thank you !

**Comment by benc-uk** [comment]
Mine was working with bridge network, and suddenly it has stopped and now I have to use `--network host`

**Comment by StefanScherer** [comment]
The IP address of the wsl2 VM seems very „random“ I haven‘t looked closer. But Docker uses a default container network 172.17.0.0/16 which may collide with the wsl2 IP address.

**Comment by benc-uk** [comment]
Yes, my IP has been all sorts, across several ranges. It changes each boot too AFAIK.

Fingers crossed the localhost support isn't far off

**Comment by metmikel** [comment]
In my case this was caused by the CIDR block of the host interface colliding with the docker interface CIDR block for the default bridge network (as suggested by @StefanScherer above).
Running `ip addr` on the host gave:

eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.17.232.2/28 brd 172.17.232.15 scope global eth0

docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0

I was able to reconfigure the default bridge network in /etc/daemon.json so that the CIDR blocks of the two interfaces didn't overlap with:
`{
 "bip": "172.17.0.1/28"
}`
(See https://docs.docker.com/network/bridge/)
After restarting the docker daemon networking worked without having to use the --network host switch.

**Comment by mardukbp** [comment]
@metmikel Thank you! That also solved my problem. In case it helps somebody, I added the config to `/etc/docker/daemon.json`.

**Comment by castrix** [comment]
This is really frustrating issue, I managed to fix it by restarting the windows

**Comment by Tuanm** [comment]
I realize that I've already set the `iptables` configuration as `false` (maybe I followed some solutions to fix a network problem before), so even if I change the `bip` in `/etc/docker/daemon.json` (as @metmikel's comment), it won't work. All steps to address this issue is removing the `iptables` configuration then restarting the wsl.

**Comment by DennisKainga** [comment]
If you are on Windows, using docker via WSL, Try restarting the docker application, ie close it completely kill the process on the task manager if you have to or just close it by right-clicking on the docker icon in your bottom right tab, also kill the running wsl instance.

**Comment by disciple-of-jesus** [comment]
For me the problem turned out to be that I wasn't signed in with my Docker account in Docker Desktop (Windows). Perhaps it helps :). Here's the error log I used to see:
```
docker pull grafana/pyroscope:1.11.0
request returned Bad Gateway for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.47/images/create?fromImage=grafana%2Fpyroscope&tag=1.11.0, check if the server supports the requested API version
```
