### ISSUE TITLE
Unable to run some wsl commands

### ISSUE THREAD

**Issue by djxvillain** [MicrosoftDocs/WSL#448]
Hello:

When I run "wsl --set-version WLinux 2" I am presented with the help page.  Same when I run "wsl -l -v."  Help please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Install WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-install.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by PatersonKopp** [comment]
Try to run the "Windows PowerShell" instead of the "CMD".

**Comment by mscraigloewen** [comment]
I suspect this is most likely because you do not have the correct Windows version. Please make sure you are using the Windows Insiders program and are on build 18917 or higher.

I'm going to close out this issue as this page is for the WSL docs, if you run into further issues with WSL please file them on the [WSL Github repo](https://github.com/microsoft/wsl).
