### ISSUE TITLE
Init Processes And (System Services Start Up Procresses)

### ISSUE THREAD

**Issue by stevebovy** [MicrosoftDocs/WSL#462]
I expect that this new vm-technology will be slower  to spin up the first-use instance

I have written a vb-script to automate the launch of my VxXsrv in conjunction with running a gnome shell instance or a gnome file-manager instance,  but I have had some difficulty resolving some of the "first-use" timing issues.

The "first-use" case always takes much longer; And during that prolonged agony it seems like nothing
is happening and/or it did not work.  Of course it would be nice to figure out how to display a temporary "Please Wait" Box,  but that seems like very complex over-kill. 

Will some consideration be given to providing  a "Windows System Services" Auto "Start/Stop"  for WSL2

And also traditional Linux Kernel boot-Up "INIIT SCRIPT PROCESSING"   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-faq.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @mscraigloewen
* Microsoft Alias: **mscraigloewen**

**Comment by mscraigloewen** [comment]
Here's a gif of how long it takes to start up WSL 2. ![WSL2](https://i1.wp.com/devblogs.microsoft.com/commandline/wp-content/uploads/sites/33/2019/05/runwsl.gif?w=640&ssl=1)

We are also tracking [running services when Windows starts](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/19243282-run-services-when-windows-starts), which I believe would encompass your request for an auto start to for WSL 2 services. 

I'll close out this issue since this is the Docs repo and is for issues related to the WSL docs! Thanks for filing.

**Comment by ahmadalli** [comment]
@craigloewen-msft the uservoice link is dead. is there any place I can get the status update?

**Comment by craigloewen-msft** [comment]
We're tracking this request here https://github.com/microsoft/WSL/issues/994 as it is likely that this work will be related to adding systemd support to WSL!
