### ISSUE TITLE
Questions on Build 18947 (pre-release)

### ISSUE THREAD

**Issue by Biswa96** [MicrosoftDocs/WSL#464]
* Why kernel path need to be absolute? Many users may not know what it is.
* What are the boundaries of assigned memory and processor values?
* What are the required file permissions for kernel and swap file?
* Can VHD file path also be assigned as kernel and swap files?
* Is `localhostForwarding` same as in WSL1?
* Are Hyper-V sockets valid now?
* Any benchmark of 9P  performance?

**Comment by mscraigloewen** [comment]
We have a blog post coming out soon that will go into more details for some of these! Here's the quick answers:

- Why kernel path need to be absolute? Many users may not know what it is.
   - w
- What are the boundaries of assigned memory and processor values?
   - For processors it's up to the number of processors you have on your machine
- What are the required file permissions for kernel and swap file?
   - Both should be accessible by your user account
- Can VHD file path also be assigned as kernel and swap files?
   - Unsure what you mean by this one. Do you mean can you store your kernel and swap files where the VHD lives? Yes absolutely!
- Is localhostForwarding same as in WSL1?
   - It's the same experience as hosting a Linux server and connecting to it in Windows as in WSL 1. More details in a blog post soon!
- Are Hyper-V sockets valid now?
   - I'd need more detail to answer this.
- Any benchmark of 9P performance?
   - Nothing formal, I'd be interested to see if you made your own. Unzipping tarballs are always great for benchmarking IO.

I'm gonna close this issue out since I believe I've addressed most of your questions, but if you have more please keep commenting!

**Comment by Biswa96** [comment]
Thank you for the quick and to-the-point answers 👍

> Can VHD file path also be assigned as kernel and swap files?

I mean will there be an option for the VHD file in `.wslconfig` file? Instead of using the `BasePath` registry string.

> Are Hyper-V sockets valid now?

I mean the things mentioned [here][1]. Will these be valid for 18947 as it is in 18197+ builds?


[1]: https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/make-integration-service

**Comment by mscraigloewen** [comment]
Ah gotcha! 
And specifying a custom path for the VHD wouldn't be in .wslconfig since those have global settings and each VHD is distro specific. 

I'm still missing context for the Hyper-V socket. What was valid in 18197+ builds with regards to WSL and Hyper-V Sockets?

Also [here's a link](https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/) to that blogpost.

**Comment by tobiaskohlbau** [comment]
I can't find the proper answer. But earlier on there was a question from some docker developer (if I remember correctly) about sockets within WSL2. He had hacked together a working solution with the technique provided by @Biswa96. @benhillis answered that that isn't the intended way to do it and that you're working on a proper way to handle this. I think @Biswa96 references to a proper way to handle socket connections between windows and wsl2.

**Comment by Biswa96** [comment]
I mean can I use AF_HYPERV as previous? Another thing, the name `.wslconfig` (text) and `wslconfig` (executable) may create confusion.

**Comment by Biswa96** [comment]
@tobiaskohlbau Hey, I didn't "hack" it. There is dedicated article using those HylerV socket. See my previous post for the link.

**Comment by Biswa96** [comment]
@tobiaskohlbau Hey, I didn't "hack" it. There is dedicated article using those Hyper-V socket. See my previous post for the link.

**Comment by mscraigloewen** [comment]
Thanks @tobiaskohlbau and @Biswa96 for the context! Yes I remember that conversation, no the Hyper-V socket connection is not valid with this build.

**Comment by tobiaskohlbau** [comment]
I didn't mean your solution, i meant the solution from the docker guy. You answered to that issue as well but I'm unable to find it. It was about that registering the application needs admin privileges. Sorry if my comment was misleading.

**Comment by Biswa96** [comment]
Another confusion. The blog post says build 18945 but Ben Hillis's commit says build 18947.

**Comment by mscraigloewen** [comment]
I've fixed this in both the commit and release!

**Comment by tobiaskohlbau** [comment]
Stupid me I've searched in the wrong repository. Just for clarification I would like to link to the discussion I've mentioned. Just in case someone later on stumble upon this.

https://github.com/microsoft/WSL/issues/4131

**Comment by Biswa96** [comment]
Another query. `System32\bash.exe` is trimmed down. The blog post did not mention that. What are the commandline option it accepts now? Is the distribution GUID also an acceptable commandline option as previous builds?

**Comment by Biswa96** [comment]
Another query. `System32\bash.exe` is trimmed down. The blog post did not mention that. What are the commandline option it accepts now?
