### ISSUE TITLE
What's WslFs?

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/WSL#465]
What's WslFs in wsl.exe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2faa612c-2d90-b3c4-0f01-e5d23c42bc04
* Version Independent ID: 3ed15eb4-f9d4-ae63-c0e6-354674e301b2
* Content: [Release Notes for Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/release-notes)
* Content Source: [WSL/release-notes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md)
* Product: **windows-subsystem-for-linux**
* GitHub Login: @benhillis

**Comment by mscraigloewen** [comment]
WSLFS stands for: Windows Subsystem for Linux File System.

It's how we store and access Linux files on your Windows machine, and is present in WSL 1. 

I'll close this issue since I've answered your question, but I'll also take a look at adding an explanation for this somewhere in the docs as well. Thanks for filing!
