### ISSUE TITLE
error 0x8007019e

### ISSUE THREAD

**Issue by giuseppegg02** [MicrosoftDocs/WSL#475]
when i tried to open linux on my windows pc it appears this error 

Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x8007019e
The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Press any key to continue...

help me plis

**Comment by craigloewen-msft** [comment]
Hello please note this repo is for issues only related to the documentation, not to technical issues. If you have technical issues please post them to our WSL Github here: https://github.com/microsoft/wsl/issues

Your error seems to be due to the fact that you do not have the Windows Subsystem for Linux optional feature enabled. Please take a look at our documentation on how to do so (like running that Powershell command).

If you have any further technical issues please open up a new one on our [WSL Github Page](https://github.com/microsoft/wsl/issues). Thanks!
