### ISSUE TITLE
Abrupt restart without asking

### ISSUE THREAD

**Issue by krishnayalavarthi** [MicrosoftDocs/WSL#504]
Running the command "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux" from powershell, restarts the machine without even asking. It should let user save the data and give a gracefull restart.

**Comment by craigloewen-msft** [comment]
What build of Windows are you running? In my experience that command prompts you on whether you'd like to restart now or not after it's finished.

**Comment by krishnayalavarthi** [comment]
Version 1809 (OS Build 17763.885)

**Comment by craigloewen-msft** [comment]
This is fixed in the latest builds, as I can confirm you are prompted. I'd recommend upgrading and that should solve your issue. If you still run into it after upgrading please feel free to reopen this on our [WSL Github repo](https://github.com/microsoft/wsl) as this one is just for the documentation. Thanks for filing! :)
