### ISSUE TITLE
\\wsl$\ubuntu18-18.04 network error in explore.exe

### ISSUE THREAD

**Issue by boan-jfm** [MicrosoftDocs/WSL#505]
When I use the powershell I can `cd \\wsl$\ubuntu-18.04` but when trying accessing the distro via explore.exe I get an error: `Network Error: Windows cannont access \\wsl$\ubuntu-18.04`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [UX Changes between WSL 1 and WSL 2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-ux-changes#feedback)
* Content Source: [WSL/wsl2-ux-changes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-ux-changes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Hi @boan-jfm, could you try closing all your WSL sessions, running `wsl --shutdown` in PowerShell, and then running `explorer.exe .` from the bash shell? Does the problem still exist then? IF yes, after restarting as well?

If it does, then I'd recommend updating to the latest insider build and then trying again.

If you're still seeing the error could you please open an issue on our [WSL github repo](https://github.com/microsoft/wsl/issues)? This one is just for the documentation, so I'll close it out since this isn't a docs issue.

Thanks! :)
