### ISSUE TITLE
Please add dates when updating the release notes

### ISSUE THREAD

**Issue by rfoust** [MicrosoftDocs/WSL#514]
Hi, just a minor request -- can the date be added to each post when a new build/update is posted on this site?   Just something simple, similar to this page:  https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-version-history
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2faa612c-2d90-b3c4-0f01-e5d23c42bc04
* Version Independent ID: 3ed15eb4-f9d4-ae63-c0e6-354674e301b2
* Content: [Release Notes for Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/release-notes#feedback)
* Content Source: [WSL/release-notes.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/release-notes.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @benhillis
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
@benhillis - Thoughts about adding a date to each Release Notes update? 
*Also, please update the metadata tag at the top of the article: "ms.date:" any time that the page is updated. Currently the date is set to "ms.date: 05/15/2020", but there have been several releases added since then. This will help the page to look more current and rank better in web search results.

**Comment by mattwojo** [comment]
Closing as WSL has moved to being release via the Microsoft Store. You can find release notes for the most recent versions of WSL here (and includes dates): https://github.com/microsoft/WSL/releases
