### ISSUE TITLE
apt-get update errors

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/WSL#532]
I am getting following errors while doing` apt-get update` command

> apt-get: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0: invalid ELF header

I have used _Ubuntu-18.04_ image for my WSL on Windows 10.

How to fix this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d83a849a-3167-a76c-7a10-caa1eb11b025
* Version Independent ID: 91d93e7d-8206-77bf-ace0-f8c44810bf17
* Content: [Troubleshooting the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/troubleshooting)
* Content Source: [WSL/troubleshooting.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/troubleshooting.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Seems to be related to this: https://github.com/microsoft/WSL/issues/4745#issuecomment-563308657

Please follow up on that thread if you're seeing similar issues!

What would help us is listing your build number (Open up CMD and run `ver`), listing any repro steps that you took for this error to occur, etc.

I'll close out this issue since it's not doc related, please follow up on the other thread for solutions. :)

**Comment by Anand-Moghe** [comment]
@craigloewen-msft Thank you very much! The process outlined in the related issue link worked like a charm for me 👍 !
