### ISSUE TITLE
Ubuntu installed twice

### ISSUE THREAD

**Issue by Rob-Echlin-Solace** [MicrosoftDocs/WSL#542]
1) Clicking on the "Ubuntu" icon in the taskbar installs Ubuntu.
2) Typing "ubuntu" in "Command Prompt" or "Windows Terminal (Preview)" installs it again.

"GetAPPXPackage" lists both locations:

```
PS C:\Users\rechlin&gt; $path = (Get-AppxPackage *Ubuntu*).InstallLocation
PS C:\Users\rechlin&gt; echo $path
C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc
C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2019.522.0_x64__79rhkp1fndgsc
```

I would like to make both work with the same installation. Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by Rob-Echlin-Solace** [comment]
Workaround:
From command prompt or Win Terminal "wsl" runs the "other" ubuntu where I have already set up .bashrc to my liking.

**Comment by craigloewen-msft** [comment]
It looks like you have an Ubuntu-18.04 and an Ubuntu instance. If you run `wsl -l` you should see a list of the current distros you have installed which should help you determine which ones are running. 

Since this isn't an issue with the docs, but is technical I'll close it out but if you have more questions please feel free to comment and I'll try and help,. (Just @ me in the message so it pops up right away :) )
