### ISSUE TITLE
Need more information about how to setup X with WSL 2

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/WSL#577]
Can not find any details on this, and end up sticking with MOBOx term. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e78ef3-d2eb-1708-d319-be5c4d72274b
* Version Independent ID: 3f3f241f-6e72-859d-3d93-e115e2de0bfb
* Content: [WSL 2 Frequently Asked Questions](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq?source=docs)
* Content Source: [WSL/wsl2-faq.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/wsl2-faq.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
We'll probably never see anything in the official docs about it since they don't officially support X server (if that changes, it would be documented then). However we did see some demos of it on WSL2 in WSLConf. I would check the Ubuntu channel on Youtube for a recording.

**Comment by buxtonpaul** [comment]
So I was doing this today. The issue I ran into was that most instructions say to grab the IP from resolv.conf, but for me that seems to be picking up the Virtual network adapter for WSL itself, which doesn't work. In the end I have created a (really dirty) python script to query ipconfig.exe and try to guess the adapter to use. I also have a VPN adapter that shows up, so had to deal with that. The logic the script uses is that if it has a Local-Link, and isn't the vEthernet adapter then it is worth trying. 

get the gist here https://gist.github.com/buxtonpaul/2074bc4c56f53cf37a27e3d59ca7a29b
add 
``` EXPORT DISPLAY=$($HOME/wsldisplay.py)) ```
to your .bashrc
Run a XServer (X410 seems nice).

**Comment by jacklh9** [comment]
Using X with WSL2 is similar to setting up for WSL1 per here:
[Get your sidekick for easily managing and launching Linux GUI apps (WSL)](https://x410.dev/cookbook/wsl/xidekick/)

... but you'll need to update the above steps with the desired display var below depending on which version of WSL you are using.

NOTE: Alternative to paid x410 X server, you can use free [VcXsrv](https://sourceforge.net/projects/vcxsrv/).

```
# WSL1
export DISPLAY=127.0.0.1:0.0
```

```
# WSL2
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0
```

SOURCES: 
- [Using X410 with WSL2](https://x410.dev/cookbook/wsl/using-x410-with-wsl2/)
- [HOWTO: Enable WSL2 and Convert Existing Pengwin Installations](https://www.whitewaterfoundry.com/blog/2019/6/12/enable-wsl2-and-convert-existing-pengwin-installations)

**Comment by ldonofriopq** [comment]
WSL2 is different from WSL1 in that the console and the X client are on different IP addresses?  I can't get the VcXsrv to  talk to the xorg no matter what I try, help!

**Comment by WSLUser** [comment]
`WSL2 is different from WSL1 in that the console and the X client are on different IP addresses? `

Yes. WSL2 relies on a light-weight version of Hyper-V, and every distro is run in a container on top of that light-weight VM infrastructure. So Windows will have one IP and all your distros will have completely different ones. It can however be mapped properly and work.

**Comment by ldonofriopq** [comment]
@WSLUser How?  here is my normal setup guide for WSL1 builds https://www.tinyurl.com/donofrioworkremmina2020 the raw text file has the setup and shows you how I set the DISPLAY variable.  I've done these same steps on my WSL2 install but even with firewall port open to the VcXsrv application it is still unable to connect ;(

**Comment by jacklh9** [comment]
@ldonofriopq 

Did you replace step 17 with the WSL2 host IP:
WSL1 == > 17.) echo "export DISPLAY=localhost:0.0" >> ~/.bashrc
WSL 2 ==> 17.) export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0

Don't forget my note on firewall setting to allow:
- Allow apps to communicate through Windows Defender Firewall
- Set Windows Defender Firewall VcXsrv windows xserver settings to work on Public & Private (and possibly Domain since you seem to be on an Enterprise network) for the X-Windows server:
 - C:\program files\vcxsrv\vcxsrv.exe

**Comment by craigloewen-msft** [comment]
WSL now includes support for GUI apps out of the box! 

Please see this tutorial for more info:
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

**Comment by ldonofriopq** [comment]
> WSL now includes support for GUI apps out of the box!
> 
> Please see this tutorial for more info: https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

How do I get to the full xfce4 desktop, not just the apps (that seem to run in their own container and sometimes stop responding (terminal and hexchat in this case)

**Comment by jacklh9** [comment]
> > WSL now includes support for GUI apps out of the box!
> > Please see this tutorial for more info: https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
> 
> How do I get to the full xfce4 desktop, not just the apps (that seem to run in their own container and sometimes stop responding (terminal and hexchat in this case)

I can't speak to running full xfce4 full desktop native per @ldonofriopq, but if you use the open-source "VcXsrv windows xserver" and configure WSL accordingly to display to it (note that WSL v1 differs from WSL v2 since v2 is a different IP), then when you launch VcXsrv, you can specify if you want a window-less environment or a windowed-fullscreen (which you want for a full XFCE environment). I use LXDE, so I don't know the XFCE command to launch the full environment, but the equivalent in LXDE is:

``
jack@myexamplewsl:~/bin cat lxde.sh
#!/bin/bash

SLEEP_SECS=10
```
# Xserver config
# 1 = if using Windows wgl (in VcXrv check "Native opengl")
# Uncomment if using other (e.g., Mesa GL: apt install mesa-utils)
# HOWEVER, don't export!
```
LIBGL_ALWAYS_INDIRECT=1
```
# WSL 1
# #export DISPLAY=localhost:0
# #export DISPLAY=localhost:$DISPLAY_NUM

### WSL 2
```
export DISPLAY=192.168.0.12:0.0

echo DISPLAY exported as: $DISPLAY
echo
echo Sleeping for $SLEEP_SECS seconds to allow previous commands to complete before starting LXDE
sleep $SLEEP_SECS

```
# DEBUG
#/usr/bin/startlxde 1> ~/lxde.log 2>&1 &

# PROD
```
/usr/bin/startlxde 1> /dev/null 2>&1 &
``

**Comment by jacklh9** [comment]
And in case anyone is wondering about the above sleep statement, this script is the final one in a chain and so it's ensuring some time for some of the commands launched into the background from prior scripts complete. Clearly setting environment vars only wouldn't necessitate all the sleeping.
