### ISSUE TITLE
Documentation for wslclient.dll

### ISSUE THREAD

**Issue by crramirez** [MicrosoftDocs/WSL#587]
Hello,

Already exist documentation for wslclient.dll? or a textfile with the function names?

I want to begin implementing my app over this DLL

Regards,
Carlos

**Comment by Biswa96** [comment]
Is it allowed to be used in an app? If yes then try this [WslClient.h](https://github.com/Biswa96/WslReverse/blob/master/wslcli/WslClient.h).

**Comment by Biswa96** [comment]
Is it allowed to use in normal projects?

**Comment by crramirez** [comment]
Well this is the text in the release notes:

> Create wslclient.dll that contains all command line functionality

So, for me it invites to be used

**Comment by Biswa96** [comment]
It means that all the command line programs for WSL e.g. wsl.exe, bash.exe, wslhost.exe, wslconfig.exe usses that wslclient.dll instead of LxssManager.dll, probably to trim the memory footprint.

If you _really_ want to use it, I have created this [WslClient.h](https://github.com/Biswa96/WslReverse/blob/master/wslcli/WslClient.h) whcih has the IWslClient interface definition.

**Comment by Biswa96** [comment]
It means that all the command line programs for WSL e.g. wsl.exe, bash.exe, wslhost.exe, wslconfig.exe uses that wslclient.dll instead of LxssManager.dll, probably to trim the memory footprint.

If you are interested in that interface, I have created this [WslClient.h](https://github.com/Biswa96/WslReverse/blob/master/wslcli/WslClient.h) which has the IWslClient interface definition.

**Comment by craigloewen-msft** [comment]
We don't have any documentation available for wslclient.dll. Thank you for filing!
