### ISSUE TITLE
Rename linux distribution on wsl

### ISSUE THREAD

**Issue by kavehAlahdin** [MicrosoftDocs/WSL#656]
I updated ubuntu18.04 to 20.04 LTS on WSL. though it is still being listed as 18.04 version using
 `wsl -l -v ` command.  I could not find how to rename it, if I have to do it manually or by some other way have it updated. 
There was nothing in the MSDocs (wsl documentation )in this regard.

**Comment by WSLUser** [comment]
This isn't a WSL Doc issue. This is an Ubuntu issue (except not really and I'll tell you why). You installed Ubuntu 18.04 from the MS Store. Therefore, even though you can perform an upgrade via CLI, your Store app was NOT updated. Just the contents within it. Therefore it will continue showing as ubuntu1804.exe. If you want it to change you'll need to uninstall 18.04 and install 20.04 from the Store. If you aren't running WSL2 however, don't bother. 20.04 is broken in WSL1 and no official word on a fix getting backported.

**Comment by TBBle** [comment]
You can also just install "Ubuntu" from the store, since you're going to manage the version yourself anyway. That'll pull in 20.04 today, and you can upgrade it yourself going forward, and then if you blow away the instance and recreate it, you'll get the version supported on the day.

It's not an ideal workflow, but it does keep the version number out of your `wsl --list`.

**Comment by craigloewen-msft** [comment]
Currently you can use `wsl --export` and then `wsl --import` to rename a distro if you prefer. This example shows a similar workflow which should give you an idea of how to use these commands:

https://craigloewen-msft.github.io/WSLTipsAndTricks/tip/install-different-drive.html
