### ISSUE TITLE
Directions Dated

### ISSUE THREAD

**Issue by marktab** [MicrosoftDocs/WSL#657]
I just enabled WSL on this new machine, and reboot is not needed.

PS C:\windows\system32&gt; Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux            

Path          :
Online        : True
RestartNeeded : False

Also, I'm seeing that the store image does not have (for example) Ubuntu 20.04 which is a stable release

https://www.microsoft.com/en-gb/p/ubuntu-2004-lts/9n6svws3rx71?cid=msft_web_chart&activetab=pivot:overviewtab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10?redirectedfrom=MSDN)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by WSLUser** [comment]
It actually is. WSL will not work correctly until it is. It shouldn't even open for you until after reboot. If this isn't the case, this is actually a bug with wsl.exe.

**Comment by marktab** [comment]
@WSLUser thanks for the insight

What do you think about the 20.04

**Comment by WSLUser** [comment]
Works fine for me. But mileage may vary. I've been using WSL2 and so far seems great. But sometimes you'll need WSL1. I haven't run into it myself but others have. Windows itself seems fine but I'm also running it in a VM, which probably makes a difference. I also use Chromium-based Edge, Windows Terminal, Win32-OpenSSH (along with WSL ssh) and VS Code Insiders with Remote-WSL extension and haven't run into any OS errors. I did initially have issues with the VS Code extension but it was easily solved. The issue stemmed from using an imported distro (Clear Linux) instead of a Store-installed one.

**Comment by mattwojo** [comment]
Sounds like this is resolved and does not require any doc updates.
Also, way late (sorry) but here's the link to 20.04 in the Store: https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71#activetab=pivot:overviewtab (I'm sure you already found it by now).
