### ISSUE TITLE
--verbose is not an option anymore

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/WSL#673]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/WSL.de-DE/issues/9
I cannot find the source en-us page.

@ajoe commented 4 hours ago — with docs.microsoft.com

using "wsl --list --verbose" doesn't work with Microsoft Windows [Version 10.0.18363.815]
"-v" or "--verbose" is not a valid option.

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Installieren von WSL 2](https://docs.microsoft.com/de-de/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by mattwojo** [comment]
Hmm... @CeciAc ... are you using these commands in PowerShell or Windows Command Prompt?

**Comment by mattwojo** [comment]
*It doesn't work from a Linux distro. I'm not an engineer, but I think it needs to be on the Windows OS side in order to inventory which distros have been installed and isn't an option as a command from one of those distros on the Linux side.

Please try it again in PowerShell or Windows Command Prompt (if that's not already where you were using it) and let me know if it works.

**Comment by mattwojo** [comment]
Closing this issue. This command works so without further information about the problem, there's nothing we can do.
