### ISSUE TITLE
document how to create an "appx" from an exported tar file

### ISSUE THREAD

**Issue by bbulkow** [MicrosoftDocs/WSL#750]
[Enter feedback here]

Missing doc step is how to create an application launch into a distribution that's been created on the command line with a particular user.

For example, I install from the app store a version of Ubuntu. I take a backup with --export, to a tar file. I move that file to another machine, and I --import. That distribution is installed, is a valid distribution, but has no appx, can't be launched from windows start, and won't launch with the "correct" user.

Please include the directions for creating an appx from a --export'd tar file that gives exactly the same end result as installing from the store.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by bbulkow** [comment]
This is really a question about how to --import back to the same state. If I can --export a running command prompt, but I can't --import it back to the same state, and only because there's a missing one line of how to create the "application", that's sad, because you've done the hard part by supporting --import and --export

**Comment by TBBle** [comment]
I think you're looking for https://github.com/microsoft/WSL-DistroLauncher? The --export and --import commands mirror each other, but they only deal with the WSL instance itself. All the [launcher/GUI integration things you're talking about](https://github.com/microsoft/WSL-DistroLauncher#launcher-outline) are handled by a launcher that each distro compiles for themselves, from a fork of WSL-DistroLauncher, that drives WSL on your behalf, but isn't part of the WSL instance.

**Comment by bbulkow** [comment]
Well, that's interesting. What I'm looking for is the ability to actually back up a WSL environment, and restore it, if I need to restore. A key part of that runtime experience is the launcher / GUI experience, sure, but how do I do it?

I've got a tarball from a --export. I know it was ubuntu18. I can run it through the command line with wsl, but I don't have the launcher associated. What next?

**Comment by TBBle** [comment]
Do you want to restore it as Ubuntu 18, or do you want to create a new launcher and AppX for your backup?

If you just want to restore your backup, e.g., in case of data loss, I would guess all you need to do `wsl --unregister ubuntu` and `wsl --import ubuntu` to replace the Ubuntu distribution data. The launcher won't know the difference, because there is no meaningful difference between a distribution created by the launcher, and one created by you from an export of that distribution. The launcher, after the initial setup, is really just running `wsl --distribution ubuntu` for you.

If you want to create a new launcher and install script, then you can use the [Getting Started instructions for WSL-DistroLauncher](https://github.com/microsoft/WSL-DistroLauncher#getting-started), and use your tarball in step 7 instead. It's possible if you want to be Ubuntu specific that they have a public fork of the launcher with their resources. I know [Debian](https://salsa.debian.org/debian/WSL) has one.

Since you don't need the install/preconfigure steps (as you're using a tarball that has already had that done to it) you could possibly grab a [third-party simpler launcher](https://github.com/yuk7/wsldl). You can just rename the executable to the name of an already-installed WSL distribution, and it will launch it on double-click effectively the same as `wsl --distribution` does.

For that matter, a shortcut to wsl.exe with the `--distribution` flag would get going most-quickly.

If you really want something that automates generation of WSL-DistroLauncher forks from an arbitrary tarball, that's better raised as a feature request against WSL-DistroLauncher than as a documentation request for WSL. as you're effectively asking for documentation of something that doesn't exist at this time.

**Comment by bbulkow** [comment]
Hm.

Yes, I can create a shortcut with -d and -u. I thought of that. Yet, there's this launcher thing. If bringing up CMD and using a shortcut is "right" way, why does the launcher even exist? The launcher must be doing something nice and fancy for me.

Replacing the data files with an import with the same distribution name seems pretty reasonable. A bit hacky, but reasonable.

What I've ended up doing is going into my "old" distro --import, sucking out the ssl keys and pem files and .rc type files, and making careful notes about all the packages I install when doing a new thing, and building from scratch otherwise. That took about 3 hours, but I guess I'm ready for the next time, when I can just start with a new distro.

I do think that it should be possible to backup and restore the entire working environment, and the working environment for WSL appears to include both the actual WSL image and the associated launcher. From a user perspective, there is no difference between "wsl qua wsl" and "wsl the launcher", so I'd expect to be able to revive the entire thing.

Yes, it seems that's a new feature request --- but should be an obvious one, no?

Thanks for the tips, I might try doing a --import and --export overriding the wsl data just for grins.

**Comment by TBBle** [comment]
The launcher is mostly for carrying the .tar.gz and doing setup stuff as part of [one-time](https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistroLauncher.cpp#L100-L115) distro [installation](https://github.com/microsoft/WSL-DistroLauncher/blob/f858909d675f8d80e0666d2258bc43abf9c5e132/DistroLauncher/DistroLauncher.cpp#L23-L56):
* [Import the .tar.gz](https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistroLauncher.cpp#L27-L30)
* [Deletes /etc/resolv.conf](https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistroLauncher.cpp#L32-L37) so WSL can generate one.
* [Create a new default user](https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistroLauncher.cpp#L39-L53), unless registering as root-only.

Since you are using `--export` with a working root, the second and third steps are already done for you, in which case you just need to `--import` again. (Unless you're importing on a different machine, in which case you'll need to delete `/etc/resolv.conf` again, I expect.)

Distributions may customise this list. I observe that [Debian](https://salsa.debian.org/debian/WSL/-/blob/master/DistroLauncher/DistroLauncher.cpp#L23-56) doesn't.

> the working environment for WSL appears to include both the actual WSL image and the associated launcher

I think this is the faulty assumption that is causing you such grief.

The launcher is separate and unaware of what you do to your WSL environment, once it has done its job of configuring its distribution. Hence the notes on the Ubuntu installer saying "Updating the App does _not_ update your Ubuntu version". (Although uninstalling _does_ delete the install. I couldn't see the code that triggers that on a brief glance.)

After installation, the launcher has no interaction with the WSL environment, it simply [sets the console title bar](https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistroLauncher.cpp#L77-L78) and runs [the equivalent of `wsl --distribution X`](https://github.com/microsoft/WSL-DistroLauncher/blob/master/DistroLauncher/DistroLauncher.cpp#L120) for you.

It would be, for example, quite reasonable for someone to use a totally different Launcher with their Linux distribution, if they so wished.

----

It sounds like what you actually want is not "DistroLauncher" but "CustomLauncher", that can launch whatever WSL distributions are installed, and something that automatically adds Start Menu shortcuts for all such detected distributions.

This is similar to the [Windows Terminal](https://github.com/microsoft/terminal) WSL support, which auto-populates its list of Linux distributions based on the [`wsl --list` list](https://github.com/microsoft/terminal/blob/57c7d1d7ae1987b586f767ff87b85af5e68fab7b/src/cascadia/TerminalApp/WslDistroGenerator.cpp#L54).

Side-note: Really strongly consider using Windows Terminal instead of the `conhost` window that comes up when you run the launcher. It's _better_, in every meaningful way except "is on your system by default".

It may also solve your use-case here, because it does detect the list of installed distributions, independent of how they were installed.

**Comment by bbulkow** [comment]
That "faulty assumption" is a belief formed only by what I've read upstream in this thread. It's a very local assumption that's easy to reverse.

What I really want is a process to --export, then --import, and get back where I was when I did the --export.

I usually launch a console from the start menu ( or moral equivalent ).

I see right now that although the user is created, the default user is not maintained ( element of /etc/wsl.config , but ... gone now? ). I can create a shortcut, if that's literally the only thing that's missing, but I just need to be told that --- it sure looks like the WSL console might be slightly different from a CMD.EXE console --- or maybe not?

My request is so simple.... --export and --import and working again.

**Comment by TBBle** [comment]
The WSL console should be the same as the `cmd` console, since as far as I can tell, it's actually a "Console app", not a "Windows app", so it runs under conhost.exe the same as `cmd` does.

If you have the Ubuntu app installed, run it to set it up as you like, and export a tarball from the distribution named 'Ubuntu', to get back to where you were from a clean state, install the Ubuntu app, import your tarball into the distribution named 'Ubuntu'.

It probably doesn't matter, but it should probably be imported into the same LocalState directory that the Ubuntu app was originally using (which should be empty if you've installed Ubuntu but never run it) so that uninstalling the Ubuntu app does a sensible thing and deletes it, as it would have done if you let it register the distribution for you.

How did the import-over-Ubuntu test go?

---

Are you thinking of [the first-run user setting](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#user)? Since config file lives inside the distro, it's up to the distro to honour it. I suspect that things have indeed shifted, and it's now up to the launcher to create a first-run user, and then after that, it's up to the user themselves to manage further user accounts. But I was unaware of this option until you mentioned it, so I honestly don't know if it's a WSL1-legacy thing, or if it's a bug in the reference launcher that it doesn't honour that setting. It absolutely _could_ honour the setting, since by the time it's up to creating users, it's already extracted the tarball and is able to run commands inside.

**Comment by craigloewen-msft** [comment]
Please see this README on how to make a WSL distro APPX. 

https://github.com/Microsoft/WSL-DistroLauncher#wsl-distro-launcher-reference-implementation

Thanks for filing!
