### ISSUE TITLE
Add-AppxPackage error: Deployment failed ... The Visual Elements extension failed while processing the Notification element

### ISSUE THREAD

**Issue by rowatc** [MicrosoftDocs/WSL#761]
Running the Add-AppxPackage command yields the following error:

>Deployment failed with HRESULT: 0x80073CF6, Package could not be registered. error 0x80070002: The Visual Elements extension failed while processing the Notification element.

I attach the log.
[log.txt](https://github.com/MicrosoftDocs/WSL/files/4798677/log.txt)

**Comment by craigloewen-msft** [comment]
Hi @rowatc could you try double clicking the Appx package file instead? 
Otherwise you could also try using the server install method, but you won't get the Appx installed on your machine (you will only get the WSL distro).

If neither of those work, could you please open an issue on the [WSL Github repo](https://github.com/microsoft/wsl) as that's where we track all of our technical issues (these boards are just for the docs). Thank you!
