### ISSUE TITLE
feature chart for vmware / virtualbox not alighed with description

### ISSUE THREAD

**Issue by aratic** [MicrosoftDocs/WSL#775]
the chart says ( both English or Chinese version), WSL2 do not work with "VirtualBox" or "VM Ware", but the quotation said it DO compatible with current one, ( also for the later cross system file system feature ), please help confirm the toggle in list, see if it's a typo, or just I understood it wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8787d64-a0f4-613d-6d9c-1a27bb2f6735
* Version Independent ID: 520a7c39-72fa-28c1-e54d-6d845087c309
* Content: [An overview on the the Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)
* Content Source: [WSL/compare-versions.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/compare-versions.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
This isn't a typo, the quotation is there since there are _preview_ versions of VMWare and VirtualBox that will support WSL 2! The current in market versions may run into collisions. The story is a bit confusing right now, we'll be sure to update this table when the preview versions become official! :) Thanks for filing this.
