### ISSUE TITLE
wsl 2 set version hangs

### ISSUE THREAD

**Issue by gvashishtha** [MicrosoftDocs/WSL#817]
When I try opening PowerShell as administrator and running the following, the command does not finish even after an hour. What am I doing wrong?

```
PS C:\WINDOWS\system32> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
```
If I open a different PowerShell window, I can see the following:

```
wsl --list --verbose
  NAME                   STATE           VERSION
* Ubuntu                 Converting      1
  Ubuntu-20.04           Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/wsl/blob/master/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by begoldsm** [comment]
I am having this exact same issue right now. It hangs and results in VMmem consuming all system memory, even after over an hour of time there is no obvious indication of progress converting the ubuntu distro to version 2.

**Comment by thornewolf** [comment]
Identical issue here. Conversion I am attempting to perform is Debian.

**Comment by abdulrahmanAlotaibi** [comment]
![image](https://user-images.githubusercontent.com/50620277/123151977-bb5e2d80-d46c-11eb-9601-92ffae6f3d1a.png)

It hangs for a long time, I switch frequently from WSL 1 to 2 and this problem is a major issue (always hanging).
And `vmmem` process as I read, concerned with VMs resource accounting, which means the virtual machines is eating my physical RAM.

![image](https://user-images.githubusercontent.com/50620277/123152988-df6e3e80-d46d-11eb-9fa4-20c4bbb8f8be.png)

📝 Using Ubuntu image for my WSL
📝 **Sometimes, the switching from WSL 1 to 2 happens in minutes after consuming a lot of my machine resources (CPU, RAM)**
📝 **many times the switching hangs for a long time (hours)**

**Comment by EltonAlvess** [comment]
Any solution? I`m facing the same issue here!

**Comment by thornewolf** [comment]
I needed to transfer any files i wanted to keep off, uninstall my WSL, then reinstall the latest verison

**Comment by craigloewen-msft** [comment]
This command can take a long time due to the size of the distribution. If you need a work around please try moving key files off the distribution and onto a drive before putting them back into your new distro.

We have also made some changes to this behaviour to help limit memory usage so I'd urge you to try this command again and if you run into technical issues please file them at https://github.com/microsoft/wsl as this repo is just for the docs. Thank you!
