### ISSUE TITLE
GUI apps ?

### ISSUE THREAD

**Issue by johne53** [MicrosoftDocs/WSL#836]
I just installed WSL2 with the Debian Linux option from [these instructions](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

I can't quite remember where I read it - but one of the supposed advantages of WSL2 (over WSL1) was that it now offers built-in support for GUI apps. However.... in my case it all still seems very "command line" based - with everything needing to be done from a bash shell.

Is that some misunderstanding on my part - or maybe a limitation with Debian? Should I try one of the alternative distros? At the very least I'd like to be able to run a file browser, such as Nautilus or whatever.

**Comment by dimithras** [comment]
[Check here](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242)

**Comment by johne53** [comment]
Many thanks **dimithras**. Do you happen to know if that page refers to both the original WSL and also WSL2? Or is it only for WSL?

The reason I'm asking is that it makes a few references to installing X11 and I've a feeling I read somewhere that WSL2 provides inbuilt support for X11 (i.e. X11 shouldn't be needed any more....)

**Comment by dimithras** [comment]
Your're welcome!

> Do you happen to know if that page refers to both the original WSL and also WSL2? Or is it only for WSL?

Huh, hard to say as the article does not mention this. At least I tried the steps using WSL-2 with [VcXSrv](https://sourceforge.net/projects/vcxsrv/).
I doubt that GUI apps can be run on without some X-server wrapper as to my knowledge WSL is not shipped with any executable to perform this. Correct me if I'm wrong, would be nice to know about the feature.

Also discussed [here](https://sourceforge.net/projects/vcxsrv/) mentioning exactly WSL-2.

Another workaround is to use remote desktop, than nothing needs to be installed on Widows side. Also mentioned in this [article](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242).
Follow the steps and also edit `/etc/xrdp/startwm.sh`, otherwise rdp connection will be dropped on each login with credentioals.

Comment out:
> #test -x /etc/X11/Xsession && exec /etc/X11/Xsession
#exec /bin/sh /etc/X11/Xsession

And add new line for **xfce4**, gdm3 or any other GUI of your preference to run on remote connection.

**Comment by craigloewen-msft** [comment]
Please see this tutorial page for answers: https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
