### ISSUE TITLE
How to upgrade wsl to version 2?

### ISSUE THREAD

**Issue by theheatDK** [MicrosoftDocs/WSL#884]
Hi,
The below page describes how to install wsl: https://docs.microsoft.com/en-us/windows/wsl/install-win10

It is mentioned that you can update to wsl 2, but it is never described how you do that.

In this section: https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-wsl-2-as-your-default-version

It is mentioned that you can set WSL 2 as your default version by running:
`wsl --set-default-version 2
`

If this also means that you upgrade to WSL 2 it would be nice if it was stated :-)

Regards Peter

**Comment by dimithras** [comment]
Hi Peter,

If you've already got wsl1 up and running, upgrade process just two steps:
- Update to new [kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel)
- Now to change wsl version to **2**:
    - as default for new distros
    `wsl --set-default-version 2`
    - change already existent distros change version without reinstalling them
    `wsl --set-version <Distro> 2`

Main difference between versions is the [kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel), so updating to new version is as simple as installing kernel and changing parameter for distros.

And you are right... Instead of clarifying this under [Update to WSL 2](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2) with a self-descriptive name, the actual step is sort of hidden in [Set WSL 2 as your default version](https://docs.microsoft.com/en-us/windows/wsl/install-win10#set-wsl-2-as-your-default-version).
Between-the-lines that section means: _If you fail to assign new version, \[as you are updating\], please get the kernel_ 🤦‍♂️

**Comment by theheatDK** [comment]
Thanks @dimithras.

I will try to update the documentation so this i clear :-)

Regards Peter
